### ISSUE TITLE
Quotation to Expression conversion does not handle comparison operators on Guid

### ISSUE THREAD

**Issue by et1975** [Microsoft/visualfsharp#1077]
I'm using Cassandra over its C# LINQ API, which allows me to submit strong-typed queries via lambda expressions. I convert F# quotations to C# expression trees like this:
```fsharp
type Quote<'T> = 
    static member X(exp:Expression<Func<'T,'a>>) = exp
```

#### Repro steps
On Windows, targeting .NET 4.5, using F# 4.0 compiler, given this data structure:
```fsharp
[<CLIMutable>]
    type Event = 
        { Id : Guid }
```
it fails to convert this lambda:
```fsharp
let newerThan (id:Guid) = Quote<Event>.X(fun d -> d.Id < id)
```
It may seem unusual to do `LessThan` on a Guid, but it corresponds to sequential time (UUID1) and makes sense in the context.

Runnable [.NET fiddle](https://dotnetfiddle.net/z2wGWn)

#### Expected behavior

Guid comparison is supported in both F# and C#, it should convert the quotation to expression as well.

#### Actual behavior
Exception is thrown:
`
An exception of type 'System.InvalidOperationException' occurred in System.Core.dll but was not handled in user code

Additional information: The binary operator LessThan is not defined for the types 'System.Guid' and 'System.Guid'.
`
Stack:
```
at System.Linq.Expressions.Expression.GetUserDefinedBinaryOperatorOrThrow(ExpressionType binaryType, String name, Expression left, Expression right, Boolean liftToNull)
at System.Linq.Expressions.Expression.GetComparisonOperator(ExpressionType binaryType, String opName, Expression left, Expression right, Boolean liftToNull)
at System.Linq.Expressions.Expression.LessThan(Expression left, Expression right, Boolean liftToNull, MethodInfo method)
at Microsoft.FSharp.Linq.RuntimeHelpers.LeafExpressionConverter.ConvExprToLinqInContext@531-6.Invoke(Tuple`2 tupledArg)
at Microsoft.FSharp.Linq.RuntimeHelpers.LeafExpressionConverter.ConvExprToLinqInContext(ConvEnv env, FSharpExpr inp)
at Microsoft.FSharp.Linq.RuntimeHelpers.LeafExpressionConverter.ConvExprToLinqInContext(ConvEnv env, FSharpExpr inp)
at Microsoft.FSharp.Linq.RuntimeHelpers.LeafExpressionConverter.QuotationToLambdaExpression[T](FSharpExpr`1 e)
```

#### Known workarounds

Code in C#

#### Related information 
* Operating system: Windows
* Branch? 
* .NET Runtime: targeting Full .NET 4.5
* Editing Tools (e.g. Visual Studio Version) VS2015 Update2
* Indications of severity

**Comment by et1975** [comment]
Sorry, closing: the operator is not implemented in c#, even though it's IComparable.
