### ISSUE TITLE
Package Load Failure while debugging C#/VB code (no F# involved)

### ISSUE THREAD

**Issue by dpoeschl** [Microsoft/visualfsharp#1533]
I was debugging Roslyn for a while, and I clicked on the Watch window (for the 3rd or 4th time that debug session) and got an F# package load failure. I have no idea what triggered the attempted load.
#### Repro steps

I don't have a reliable repro. Just what I described above.
#### Expected behavior

Debugging C#/VB shouldn't load the F# package in the first place, and loading the package shouldn't fail.
#### Actual behavior

The F# package attempts to load for some reason, then fails to do so.
#### Known workarounds

Just ignore the problem and continue on debugging
#### Related information
- Editing Tools (e.g. Visual Studio Version): VS "15" Preview 4
#### Stack trace

<details>
 <summary>

From the ActivityLog.xml</summary>

CreateInstance failed for package [FSharpPackage]Source: &apos;mscorlib&apos; Description: Exception has been thrown by the target of an invocation.
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---&gt; System.IO.FileNotFoundException: Could not load file or assembly &apos;FSharp.Core, Version=4.4.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos; or one of its dependencies. The system cannot find the file specified.
  at Microsoft.VisualStudio.FSharp.LanguageService.FSharpPackage..ctor()
  --- End of inner exception stack trace ---
  at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean&amp; canBeCached, RuntimeMethodHandleInternal&amp; ctor, Boolean&amp; bNeedSecurityCheck)
  at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark&amp; stackMark)
  at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark&amp; stackMark)
  at System.Activator.CreateInstance(Type type, Boolean nonPublic)
  at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark&amp; stackMark)
  at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
  at System.Activator.CreateInstanceFromInternal(String assemblyFile, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo)
  at System.AppDomain.CreateInstanceFrom(String assemblyFile, String typeName)System.IO.FileNotFoundException: Could not load file or assembly &apos;FSharp.Core, Version=4.4.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos; or one of its dependencies. The system cannot find the file specified.
File name: &apos;FSharp.Core, Version=4.4.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos;
  at Microsoft.VisualStudio.FSharp.LanguageService.FSharpPackage..ctor()
</details>

**Comment by dsyme** [comment]
Closing for lack of reliable repro
