### ISSUE TITLE
Error messages are duplicated in tooltips

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#1790]
VS 2017 RC:

![image](https://cloud.githubusercontent.com/assets/873919/20462850/e30e2a24-af37-11e6-892c-ace44ced1501.png)

**Comment by vasily-kirichenko** [comment]
A variation:

![image](https://cloud.githubusercontent.com/assets/873919/20462859/08c63a9a-af38-11e6-8504-51ad7204a670.png)

**Comment by vasily-kirichenko** [comment]
Fixed in https://github.com/Microsoft/visualfsharp/pull/1929

**Comment by dsyme** [comment]
Leaving open until PR is accepted

**Comment by dsyme** [comment]
Hey @vasily-kirichenko - here are the new errors in the CI
```
1) Failed : Microsoft.VisualStudio.FSharp.Editor.Tests.Roslyn.DocumentDiagnosticAnalyzerTests.Error_Expression_IllegalIntegerLiteral
  There should be exactly one error generated
  Expected: 1
  But was:  0
at Microsoft.VisualStudio.FSharp.Editor.Tests.Roslyn.DocumentDiagnosticAnalyzerTests.VerifyDiagnosticBetweenMarkers(String fileContents, String expectedMessage, DiagnosticSeverity expectedSeverity) in D:\j\workspace\release_ci_pa---3f142ccc\vsintegration\tests\unittests\DocumentDiagnosticAnalyzerTests.fs:line 65
at Microsoft.VisualStudio.FSharp.Editor.Tests.Roslyn.DocumentDiagnosticAnalyzerTests.Error_Expression_IllegalIntegerLiteral() in D:\j\workspace\release_ci_pa---3f142ccc\vsintegration\tests\unittests\DocumentDiagnosticAnalyzerTests.fs:line 83

2) Failed : Microsoft.VisualStudio.FSharp.Editor.Tests.Roslyn.DocumentDiagnosticAnalyzerTests.Error_Expression_IncompleteDefine
  There should be exactly one error generated
  Expected: 1
  But was:  0
at Microsoft.VisualStudio.FSharp.Editor.Tests.Roslyn.DocumentDiagnosticAnalyzerTests.VerifyDiagnosticBetweenMarkers(String fileContents, String expectedMessage, DiagnosticSeverity expectedSeverity) in D:\j\workspace\release_ci_pa---3f142ccc\vsintegration\tests\unittests\DocumentDiagnosticAnalyzerTests.fs:line 65
at Microsoft.VisualStudio.FSharp.Editor.Tests.Roslyn.DocumentDiagnosticAnalyzerTests.Error_Expression_IncompleteDefine() in D:\j\workspace\release_ci_pa---3f142ccc\vsintegration\tests\unittests\DocumentDiagnosticAnalyzerTests.fs:line 92

3) Failed : Microsoft.VisualStudio.FSharp.Editor.Tests.Roslyn.DocumentDiagnosticAnalyzerTests.Error_Expression_KeywordAsValue
  There should be exactly one error generated
  Expected: 1
  But was:  0
at Microsoft.VisualStudio.FSharp.Editor.Tests.Roslyn.DocumentDiagnosticAnalyzerTests.VerifyDiagnosticBetweenMarkers(String fileContents, String expectedMessage, DiagnosticSeverity expectedSeverity) in D:\j\workspace\release_ci_pa---3f142ccc\vsintegration\tests\unittests\DocumentDiagnosticAnalyzerTests.fs:line 65
at Microsoft.VisualStudio.FSharp.Editor.Tests.Roslyn.DocumentDiagnosticAnalyzerTests.Error_Expression_KeywordAsValue() in D:\j\workspace\release_ci_pa---3f142ccc\vsintegration\tests\unittests\DocumentDiagnosticAnalyzerTests.fs:line 100

4) Failed : Microsoft.VisualStudio.FSharp.Editor.Tests.Roslyn.DocumentDiagnosticAnalyzerTests.Error_Identifer_IllegalFloatPointLiteral
  There should be exactly one error generated
  Expected: 1
  But was:  0
at Microsoft.VisualStudio.FSharp.Editor.Tests.Roslyn.DocumentDiagnosticAnalyzerTests.VerifyDiagnosticBetweenMarkers(String fileContents, String expectedMessage, DiagnosticSeverity expectedSeverity) in D:\j\workspace\release_ci_pa---3f142ccc\vsintegration\tests\unittests\DocumentDiagnosticAnalyzerTests.fs:line 65
at Microsoft.VisualStudio.FSharp.Editor.Tests.Roslyn.DocumentDiagnosticAnalyzerTests.Error_Identifer_IllegalFloatPointLiteral() in D:\j\workspace\release_ci_pa---3f142ccc\vsintegration\tests\unittests\DocumentDiagnosticAnalyzerTests.fs:line 220

5) Failed : Microsoft.VisualStudio.FSharp.Editor.Tests.Roslyn.DocumentDiagnosticAnalyzerTests.Error_Type_WithoutName
  There should be exactly one error generated
  Expected: 1
  But was:  0
at Microsoft.VisualStudio.FSharp.Editor.Tests.Roslyn.DocumentDiagnosticAnalyzerTests.VerifyDiagnosticBetweenMarkers(String fileContents, String expectedMessage, DiagnosticSeverity expectedSeverity) in D:\j\workspace\release_ci_pa---3f142ccc\vsintegration\tests\unittests\DocumentDiagnosticAnalyzerTests.fs:line 65
at Microsoft.VisualStudio.FSharp.Editor.Tests.Roslyn.DocumentDiagnosticAnalyzerTests.Error_Type_WithoutName() in D:\j\workspace\release_ci_pa---3f142ccc\vsintegration\tests\unittests\DocumentDiagnosticAnalyzerTests.fs:line 109

6) Failed : Microsoft.VisualStudio.FSharp.Editor.Tests.Roslyn.DocumentDiagnosticAnalyzerTests.ExtraEndif
  There should be exactly one error generated
  Expected: 1
  But was:  0
at Microsoft.VisualStudio.FSharp.Editor.Tests.Roslyn.DocumentDiagnosticAnalyzerTests.VerifyDiagnosticBetweenMarkers(String fileContents, String expectedMessage, DiagnosticSeverity expectedSeverity) in D:\j\workspace\release_ci_pa---3f142ccc\vsintegration\tests\unittests\DocumentDiagnosticAnalyzerTests.fs:line 65
at Microsoft.VisualStudio.FSharp.Editor.Tests.Roslyn.DocumentDiagnosticAnalyzerTests.ExtraEndif() in D:\j\workspace\release_ci_pa---3f142ccc\vsintegration\tests\unittests\DocumentDiagnosticAnalyzerTests.fs:line 310

7) Failed : Microsoft.VisualStudio.FSharp.Editor.Tests.Roslyn.DocumentDiagnosticAnalyzerTests.Squiggles_HashIfWithMultilineComment
  There should be exactly one error generated
  Expected: 1
  But was:  0
at Microsoft.VisualStudio.FSharp.Editor.Tests.Roslyn.DocumentDiagnosticAnalyzerTests.VerifyErrorAtMarker(String fileContents, String expectedMarker, FSharpOption`1 expectedMessage) in D:\j\workspace\release_ci_pa---3f142ccc\vsintegration\tests\unittests\DocumentDiagnosticAnalyzerTests.fs:line 50
at Microsoft.VisualStudio.FSharp.Editor.Tests.Roslyn.DocumentDiagnosticAnalyzerTests.Squiggles_HashIfWithMultilineComment() in D:\j\workspace\release_ci_pa---3f142ccc\vsintegration\tests\unittests\DocumentDiagnosticAnalyzerTests.fs:line 349

8) Failed : Microsoft.VisualStudio.FSharp.Editor.Tests.Roslyn.DocumentDiagnosticAnalyzerTests.Squiggles_HashIfWithUnexpected
  There should be exactly one error generated
  Expected: 1
  But was:  0
at Microsoft.VisualStudio.FSharp.Editor.Tests.Roslyn.DocumentDiagnosticAnalyzerTests.VerifyErrorAtMarker(String fileContents, String expectedMarker, FSharpOption`1 expectedMessage) in D:\j\workspace\release_ci_pa---3f142ccc\vsintegration\tests\unittests\DocumentDiagnosticAnalyzerTests.fs:line 50
at Microsoft.VisualStudio.FSharp.Editor.Tests.Roslyn.DocumentDiagnosticAnalyzerTests.Squiggles_HashIfWithUnexpected() in D:\j\workspace\release_ci_pa---3f142ccc\vsintegration\tests\unittests\DocumentDiagnosticAnalyzerTests.fs:line 359

9) Failed : Microsoft.VisualStudio.FSharp.Editor.Tests.Roslyn.DocumentDiagnosticAnalyzerTests.Squiggles_HashNotFirstSymbol_Endif
  There should be exactly one error generated
  Expected: 1
  But was:  0
at Microsoft.VisualStudio.FSharp.Editor.Tests.Roslyn.DocumentDiagnosticAnalyzerTests.VerifyErrorAtMarker(String fileContents, String expectedMarker, FSharpOption`1 expectedMessage) in D:\j\workspace\release_ci_pa---3f142ccc\vsintegration\tests\unittests\DocumentDiagnosticAnalyzerTests.fs:line 50
at Microsoft.VisualStudio.FSharp.Editor.Tests.Roslyn.DocumentDiagnosticAnalyzerTests.Squiggles_HashNotFirstSymbol_Endif() in D:\j\workspace\release_ci_pa---3f142ccc\vsintegration\tests\unittests\DocumentDiagnosticAnalyzerTests.fs:line 336

10) Failed : Microsoft.VisualStudio.FSharp.Editor.Tests.Roslyn.DocumentDiagnosticAnalyzerTests.Squiggles_HashNotFirstSymbol_If
  There should be exactly one error generated
  Expected: 1
  But was:  0
at Microsoft.VisualStudio.FSharp.Editor.Tests.Roslyn.DocumentDiagnosticAnalyzerTests.VerifyErrorAtMarker(String fileContents, String expectedMarker, FSharpOption`1 expectedMessage) in D:\j\workspace\release_ci_pa---3f142ccc\vsintegration\tests\unittests\DocumentDiagnosticAnalyzerTests.fs:line 50
at Microsoft.VisualStudio.FSharp.Editor.Tests.Roslyn.DocumentDiagnosticAnalyzerTests.Squiggles_HashNotFirstSymbol_If() in D:\j\workspace\release_ci_pa---3f142ccc\vsintegration\tests\unittests\DocumentDiagnosticAnalyzerTests.fs:line 323
```

**Comment by vasily-kirichenko** [comment]
@dsyme I've fixed the tests.

**Comment by dsyme** [comment]
Super thanks
