### ISSUE TITLE
EnableOpenSource VSIX does not install in VS2015 CTP 5

### ISSUE THREAD

**Issue by KevinRansom** [Microsoft/visualfsharp#188]
Build and Debug F# OSS using deployment.sln does not actually install the EnableOssDebug vsix.

**Comment by latkin** [comment]
Is the title a typo? Did you mean "does *not* install"?

**Comment by dsyme** [comment]
This may be a separate issue, but I just got a few errors after following the instructions in DEVGUIDE.md (basically build vsintegration, run ```debug\net40\bin\EnableOpenSource.vsix```)

I think the DEVGUIDE.md must be missing a step somehow.  I'll try to dig into it

This error in the F# Interactive window:

	Exception details:
	System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.FileNotFoundException: Could not load file or assembly 'FSharp.Compiler.Server.Shared, Version=4.4.0.9055, Culture=neutral, PublicKeyToken=f536804aa0eb945b' or one of its dependencies. The system cannot find the file specified.
	   at Microsoft.VisualStudio.FSharp.Interactive.Session.createSessionProcess()
	   at Microsoft.VisualStudio.FSharp.Interactive.Session.restart@402.Invoke(Unit unitVar0)
	   at Microsoft.VisualStudio.FSharp.Interactive.Session.createSessions@440-5.Microsoft-VisualStudio-FSharp-Interactive-Session-Sessions-Restart()
	   at Microsoft.VisualStudio.FSharp.Interactive.FsiToolWindow..ctor()
	   --- End of inner exception stack trace ---
	   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
	   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
	   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
	   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
	   at System.Activator.CreateInstance(Type type)
	   at Microsoft.VisualStudio.Shell.Package.CreateToolWindow(Type toolWindowType, Int32 id, ProvideToolWindowAttribute tool)
	   at Microsoft.VisualStudio.Shell.Package.FindToolWindow(Type toolWindowType, Int32 id, Boolean create, ProvideToolWindowAttribute tool)
	   at Microsoft.VisualStudio.Shell.Package.Microsoft.VisualStudio.Shell.Interop.IVsToolWindowFactory.CreateToolWindow(Guid& toolWindowType, UInt32 id)
	   at Microsoft.VisualStudio.Platform.WindowManagement.WindowFrame.ConstructContent()

and this when I open an F# script

![capture](https://cloud.githubusercontent.com/assets/7204669/5990126/a61b9a26-a970-11e4-9066-73dd8431238e.JPG)

**Comment by dsyme** [comment]
(I didn't have VS2015 CTP5 installed, will try that now)

**Comment by KevinRansom** [comment]
This was fixed with:  https://github.com/Microsoft/visualfsharp/issues/188

![debugging](https://cloud.githubusercontent.com/assets/5175830/6094537/c65a146c-aee2-11e4-9e24-c8d5d2da9a58.jpg)

**Comment by KevinRansom** [comment]
I need to revert the description.

**Comment by KevinRansom** [comment]
The fix integrates FSI into the F5 build experience.  It doesn't integrate the compilers yet.

**Comment by KevinRansom** [comment]
Merged fix for FSI and opened new issue to integrate the compilers.
