### ISSUE TITLE
build.cmd coreclr test fails

### ISSUE THREAD

**Issue by KevinRansom** [Microsoft/visualfsharp#1948]
With

It shouldn't be running net40 tests.

````
"c:\kevinransom\visualfsharp\packages\NUnit.Console.3.0.0\tools\nunit3-console.exe" --verbose "c:\kevinransom\visualfsharp\release\net40\bin\FSharp.Tests.FSharpSuite.DrivingCoreCLR.dll" --framework:V4.0 --work:"c:\kevinransom\visualfsharp\release\net40\bin"    --result:"c:\kevinransom\visualfsharp\tests\TestResults\test-coreclr-fsharp-results.xml;format=nunit3"
NUnit Console Runner 3.0.5797
Copyright (C) 2015 Charlie Poole

Runtime Environment
   OS Version: Microsoft Windows NT 10.0.14393.0
  CLR Version: 4.0.30319.42000

Test Files
    c:\kevinransom\visualfsharp\release\net40\bin\FSharp.Tests.FSharpSuite.DrivingCoreCLR.dll

Agent process 13120 starting
Running under version 4.0.30319.42000, Net 4.5
Agent process 13120 exiting

Errors and Failures

1) Error : c:\kevinransom\visualfsharp\release\net40\bin\FSharp.Tests.FSharpSuite.DrivingCoreCLR.dll
System.Exception : couldn't find c:\kevinransom\visualfsharp\tests\fsharp\..\..\release\net40\bin\fsc.exe
   at Microsoft.FSharp.Core.Operators.FailWith[T](String message) in c:\kevinransom\visualfsharp\src\fsharp\FSharp.Core\prim-types.fs:line 3828
   at TestFramework.config(String configurationName, FSharpMap`2 envVars) in c:\kevinransom\visualfsharp\tests\fsharp\test-framework.fs:line 184
   at TestFramework.initializeSuite() in c:\kevinransom\visualfsharp\tests\fsharp\test-framework.fs:line 260
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at TestFramework.InitializeSuiteAttribute.BeforeTest(ITest details) in c:\kevinransom\visualfsharp\tests\fsharp\test-framework.fs:line 277
   at NUnit.Framework.Internal.Commands.OneTimeSetUpCommand.Execute(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.ApplyChangesToContextCommand.Execute(TestExecutionContext context)

2) Error : FSharp-Tests-Core+CoreTests.access-FSC_BASIC
OneTimeSetUp: System.Exception : couldn't find c:\kevinransom\visualfsharp\tests\fsharp\..\..\release\net40\bin\fsc.exe

Run Settings
    RuntimeFramework: V4.0
    WorkDirectory: c:\kevinransom\visualfsharp\release\net40\bin
    Verbose: True
    NumberOfTestWorkers: 4

Test Run Summary
    Overall result: Failed
   Tests run: 1, Passed: 0, Errors: 1, Failures: 0, Inconclusive: 0
     Not run: 0, Invalid: 0, Ignored: 0, Explicit: 0, Skipped: 0
  Start time: 2016-12-05 22:44:10Z
    End time: 2016-12-05 22:44:10Z
    Duration: 0.195 seconds

Results (nunit3) saved as c:\kevinransom\visualfsharp\tests\TestResults\test-coreclr-fsharp-results.xml
````

**Comment by KevinRansom** [comment]
fixed
