### ISSUE TITLE
Cannot install local Visual F# Tools on RC2

### ISSUE THREAD

**Issue by cartermp** [Microsoft/visualfsharp#2025]
1. Install F# through VS Installer.
2. Build a release build of Visual F# tools.
3. Uninstall F#.
4. Run `VSIXInstaller.exe /a release\net40\bin\VisualFSharpOpenSource.vsix` to install locally.

**Expectected:** I can open an F# project and work in it with the new tools installed locally.

**Actual:** Projects fail to load, some as "Incompatible" and some as "Unavailable".

![projects-incompatible](https://cloud.githubusercontent.com/assets/6309070/21246283/9ab18c7c-c2dc-11e6-9938-1efa64ab1e53.PNG)

**Comment by cloudRoutine** [comment]
![](http://i.imgur.com/WEvqUTs.png)

```
12/15/2016 9:25:37 PM - Microsoft VSIX Installer
12/15/2016 9:25:37 PM - -------------------------------------------
12/15/2016 9:25:38 PM - Initializing Install...
12/15/2016 9:25:38 PM - Extension Details...
12/15/2016 9:25:38 PM - 	Identifier         : VisualFSharp
12/15/2016 9:25:38 PM - 	Name               : Visual F# Tools
12/15/2016 9:25:38 PM - 	Author             : Microsoft.VisualFSharpTools
12/15/2016 9:25:38 PM - 	Version            : 15.4.1.9055
12/15/2016 9:25:38 PM - 	Description        : Deploy Visual F# Tools templates to Visual Studio
12/15/2016 9:25:38 PM - 	Locale             : en-US
12/15/2016 9:25:38 PM - 	MoreInfoURL        : 
12/15/2016 9:25:38 PM - 	InstalledByMSI     : False
12/15/2016 9:25:38 PM - 	SupportedFrameworkVersionRange : [4.6,)
12/15/2016 9:25:38 PM - 
12/15/2016 9:25:38 PM - 	SignatureState     : Unsigned
12/15/2016 9:25:38 PM - 	Supported Products : 
12/15/2016 9:25:38 PM - 		Microsoft.VisualStudio.Pro
12/15/2016 9:25:38 PM - 			Version : [15.0]
12/15/2016 9:25:38 PM - 
12/15/2016 9:25:38 PM - 	References         : 
12/15/2016 9:25:38 PM - Signature Details...
12/15/2016 9:25:38 PM - 	Extension is not signed.
12/15/2016 9:25:38 PM - 
12/15/2016 9:25:38 PM - Searching for applicable products...
12/15/2016 9:25:39 PM - Found installed product - Microsoft Visual Studio Professional 2013
12/15/2016 9:25:39 PM - Found installed product - Microsoft Visual Studio 2013 Shell (Integrated)
12/15/2016 9:25:39 PM - Found installed product - Microsoft Visual Studio Community 2015
12/15/2016 9:25:39 PM - Found installed product - Microsoft Visual Studio 2015 Shell (Integrated)
12/15/2016 9:25:39 PM - Found installed product - Global Location
12/15/2016 9:25:39 PM - Found installed product - ssms
12/15/2016 9:25:39 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.InitializeInstall(Boolean isRepairSupported)
   at VSIXInstaller.App.InitializeInstall()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
```

**Comment by cartermp** [comment]
Closing this for now - will re-open/rename if I get the same issues on RC3.  I know @brettfo has been doing a lot of setup work and may have this resolved.
