### ISSUE TITLE
Cannot uninstall from Tools and Extensions

### ISSUE THREAD

**Issue by cartermp** [Microsoft/visualfsharp#2152]
1. Install .NET Desktop and Visual Studio Extensibility workloads with F# checked.
2. Uninstall Visual F# Tools from Extensions and Updates.

**Expected:**

It uninstalls without error.

**Actual:**

It fails.  Here's the log:

```
1/3/2017 10:33:05 AM - Microsoft VSIX Installer
1/3/2017 10:33:05 AM - -------------------------------------------
1/3/2017 10:33:05 AM - vsixinstaller.exe version:
1/3/2017 10:33:05 AM - 15.0.26014.0 built by: D15REL
1/3/2017 10:33:05 AM - -------------------------------------------
1/3/2017 10:33:05 AM - Command line parameters:
1/3/2017 10:33:05 AM - C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\vsixinstaller.exe,/appidinstallpath:C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\devenv.exe,/skuName:Community,/skuVersion:15.0.26014.0,/appidname:Microsoft Visual Studio Community 2017 RC,/u:VisualFSharp
1/3/2017 10:33:05 AM - -------------------------------------------
1/3/2017 10:33:05 AM - Microsoft VSIX Installer
1/3/2017 10:33:05 AM - -------------------------------------------
1/3/2017 10:33:06 AM - Initializing Uninstall...
1/3/2017 10:33:06 AM - Extension Details...
1/3/2017 10:33:06 AM - 	Identifier         : VisualFSharp
1/3/2017 10:33:06 AM - 	Name               : Visual F# Tools
1/3/2017 10:33:06 AM - 	Author             : Microsoft.VisualFSharpTools
1/3/2017 10:33:06 AM - 	Version            : 15.4.1.0
1/3/2017 10:33:06 AM - 	Description        : Deploy Visual F# Tools templates to Visual Studio
1/3/2017 10:33:06 AM - 	Locale             : en-US
1/3/2017 10:33:06 AM - 	MoreInfoURL        : 
1/3/2017 10:33:06 AM - 	InstalledByMSI     : False
1/3/2017 10:33:06 AM - 	SupportedFrameworkVersionRange : [4.6,)
1/3/2017 10:33:06 AM - 
1/3/2017 10:33:06 AM - 	Supported Products : 
1/3/2017 10:33:06 AM - 		Microsoft.VisualStudio.Pro
1/3/2017 10:33:06 AM - 			Version : [15.0]
1/3/2017 10:33:06 AM - 
1/3/2017 10:33:06 AM - 	References         : 
1/3/2017 10:33:06 AM - 	Prerequisites      : 
1/3/2017 10:33:06 AM - 		-------------------------------------------------------
1/3/2017 10:33:06 AM - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
1/3/2017 10:33:06 AM - 		Name         : Visual Studio core editor
1/3/2017 10:33:06 AM - 		Version      : [15.0,16.0)
1/3/2017 10:33:06 AM - 
1/3/2017 10:33:06 AM - 
1/3/2017 10:33:12 AM - The following target products have been selected...
1/3/2017 10:33:12 AM - 	Microsoft Visual Studio Community 2017 RC
1/3/2017 10:33:12 AM - 
1/3/2017 10:33:12 AM - Uninstalling 'Visual F# Tools', version 15.4.1.0.
1/3/2017 10:33:13 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64 declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64 doesn't declare a chip
1/3/2017 10:33:13 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
1/3/2017 10:33:13 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
1/3/2017 10:33:13 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
1/3/2017 10:33:13 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
1/3/2017 10:33:13 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
1/3/2017 10:33:13 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
1/3/2017 10:33:13 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
1/3/2017 10:33:13 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
1/3/2017 10:33:13 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
1/3/2017 10:33:13 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
1/3/2017 10:33:13 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
1/3/2017 10:33:13 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
1/3/2017 10:33:13 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
1/3/2017 10:33:13 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
1/3/2017 10:33:13 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.Extensions.X64 declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.Extensions.X64 doesn't declare a chip
1/3/2017 10:33:13 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64 declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64 doesn't declare a chip
1/3/2017 10:33:13 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
1/3/2017 10:33:13 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
1/3/2017 10:33:13 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
1/3/2017 10:33:13 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
1/3/2017 10:33:13 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
1/3/2017 10:33:13 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
1/3/2017 10:33:13 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
1/3/2017 10:33:13 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
1/3/2017 10:33:13 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
1/3/2017 10:33:13 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
1/3/2017 10:33:13 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
1/3/2017 10:33:13 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
1/3/2017 10:33:13 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
1/3/2017 10:33:13 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
1/3/2017 10:33:13 AM - Dependency Microsoft.VisualCpp.CodeAnalysis.Extensions.X64 declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.Extensions.X64 doesn't declare a chip
1/3/2017 10:33:14 AM - System.InvalidOperationException: The VSIX's catalog does not include a 'Component' which is required for install/uninstall.
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.PerformSetupEngineUnInstall(IInstalledExtension extension, Boolean markAsPackComponent)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.UninstallInternal(IInstalledExtension extension, Boolean forceDelete, Version targetedVSVersion)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.Uninstall(IInstalledExtension extension, Version targetedVSVersion)
   at VSIXInstaller.InstallProgressPage.UninstallVsix(String vsixId, SupportedVSSKU targetSku, IProgress`1 progress)
```

**Comment by brettfo** [comment]
Likely fixed, I was able to do this on a build from 3 days ago.

**Comment by forki** [comment]
Imho "likely" is a bit too much handwaving here. 

This is a really really important issue given that we assume all F# users will have to install a new vsix after RTM. Given @vasily-kirichenko fixes to code completion, there is just no other sane recommendation after RTM other than "use this vsix instead".

**Comment by vasily-kirichenko** [comment]
I agree with @forki, it's absolutely critical to confirm that Full VSIX can be installed on RC3/RTW. If that's not the case, users will stuck with RC2, which barely usable, till Update 1.

**Comment by forki** [comment]
I wonder if this vsix could be pushed to VS gallery for update notification.

**Comment by cartermp** [comment]
I can confirm this is fixed for me on the internal build RC3 and RTW builds; will reopen if it fails when those are public, though.
