### ISSUE TITLE
Visual Studio crash when using 'namespace global'

### ISSUE THREAD

**Issue by dhwed** [Microsoft/visualfsharp#2272]
If you create a new blank .fs file and then type `namespace global` in it, Visual Studio crashes.  I'm using latest master with Visual Studio 2017 RC2.

Here's the error from the Windows Event Log:

Application: devenv.exe
Framework Version: v4.0.30319
Description: The application requested process termination through System.Environment.FailFast(string message).
Message: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.Editor.Implementation.Structure.AbstractStructureTaggerProvider`1.<ProduceTagsAsync>d__6.MoveNext()
Stack:
   at System.Environment.FailFast(System.String, System.Exception)
   at Microsoft.CodeAnalysis.FailFast.OnFatalException(System.Exception)
   at Microsoft.CodeAnalysis.ErrorReporting.FatalError.Report(System.Exception, System.Action`1<System.Exception>)
   at Microsoft.CodeAnalysis.ErrorReporting.FatalError.ReportUnlessCanceled(System.Exception)
   at Microsoft.CodeAnalysis.Editor.Implementation.Structure.AbstractStructureTaggerProvider`1+<ProduceTagsAsync>d__6[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext()
   at Microsoft.CodeAnalysis.Editor.Implementation.Structure.AbstractStructureTaggerProvider`1+<ProduceTagsAsync>d__6[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.InvokeMoveNext(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action, Boolean, System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task.FinishStageThree()
   at System.Threading.Tasks.Task`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].TrySetResult(System.__Canon)
   at System.Threading.Tasks.TaskCompletionSource`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].TrySetResult(System.__Canon)
   at Microsoft.FSharp.Control.CancellationTokenOps+a@1334-5[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.__Canon)
   at Microsoft.FSharp.Control.AsyncBuilderImpl+args@825-1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.__Canon)
   at <StartupCode$FSharp-Core>.$Control.loop@427-51(Microsoft.FSharp.Control.Trampoline, Microsoft.FSharp.Core.FSharpFunc`2<Microsoft.FSharp.Core.Unit,Microsoft.FSharp.Control.FakeUnitValue>)
   at Microsoft.FSharp.Control.Trampoline.ExecuteAction(Microsoft.FSharp.Core.FSharpFunc`2<Microsoft.FSharp.Core.Unit,Microsoft.FSharp.Control.FakeUnitValue>)
   at Microsoft.FSharp.Control.TrampolineHolder.Protect(Microsoft.FSharp.Core.FSharpFunc`2<Microsoft.FSharp.Core.Unit,Microsoft.FSharp.Control.FakeUnitValue>)
   at Microsoft.FSharp.Control.TaskHelpers.continuation@1543[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](Boolean, Microsoft.FSharp.Control.AsyncParams`1<System.__Canon>, System.Threading.Tasks.Task`1<System.__Canon>)
   at Microsoft.FSharp.Control.TaskHelpers+continueWith@1553[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Threading.Tasks.Task`1<System.__Canon>)
   at System.Threading.Tasks.ContinuationTaskFromResultTask`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.Tasks.Task.ExecutionContextCallback(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean)
   at System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

**Comment by forki** [comment]
I can reproduce.

**Comment by forki** [comment]
even after fixing first issue it crashing on next location - will try to fix that tomorrow

**Comment by forki** [comment]
can you please try https://github.com/Microsoft/visualfsharp/pull/2273 ?

**Comment by cartermp** [comment]
FYI @Pilchie

**Comment by forki** [comment]
@dhwed please let me know if this works for you. It looks like there are couple of places where this can go wrong

**Comment by dhwed** [comment]
@forki #2273 fixes the issue for me; thanks.

**Comment by dhwed** [comment]
Actually, while the crash goes away, there's now no outlining in any files that use the global namespace.

**Comment by forki** [comment]
Ok. Do you have a minimal sample / Screenshots of what you mean? I guess my
"filter" is a bit too hard.

Am 16.01.2017 7:51 nachm. schrieb "David" <notifications@github.com>:

**Comment by dhwed** [comment]
@forki Sure, take a look:

![image](https://cloud.githubusercontent.com/assets/10184638/21996113/42d5e1d0-dbee-11e6-9990-8bfc84cb77cf.png)

Note that the expand/collapse boxes and the dashed vertical lines disappear when the namespace is `global`.

**Comment by cartermp** [comment]
@dhwed Can you create a separate issue for this?  Just for tracking purposes I'd like to split this out from the crashing bug.

**Comment by dhwed** [comment]
I've created #2274

**Comment by cartermp** [comment]
Thanks @dhwed!

**Comment by Pilchie** [comment]
Tagging @cyrusnajmabadi, but I think we need to look at the inner exception there, and see outlining block the F# language service is trying to create in that case.

**Comment by forki** [comment]
The exception was coming from fsharp analyzer code doing wrong assumptions about the identifier. It's not related to roslyn.

**Comment by forki** [comment]
Tomorrow I will try to reactivate the roslyn features for this case. Was a bit in a hurry today so I "just" made the IDE crash go away.

**Comment by Pilchie** [comment]
Thanks @forki!

**Comment by forki** [comment]
https://github.com/Microsoft/visualfsharp/pull/2278 activates the roslyn features again. Seems to work fine.
