### ISSUE TITLE
devenv.exe crash on Microsoft.VisualStudio.Package.Colorizer.GetLineInfo

### ISSUE THREAD

**Issue by smoothdeveloper** [Microsoft/visualfsharp#2391]
I don't have much info, my steps where:

* open VS2017 RC4
* open a .fsx
* select all and evaluate

After a short while, VS crashed, this is what I found in Windows Event Viewer:

```
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Runtime.InteropServices.COMException
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32, IntPtr)
   at Microsoft.VisualStudio.Package.Colorizer.GetLineInfo(Microsoft.VisualStudio.TextManager.Interop.IVsTextLines, Int32, Microsoft.VisualStudio.TextManager.Interop.IVsTextColorState)
   at Microsoft.VisualStudio.Package.Source.GetWordExtent(Int32, Int32, Microsoft.VisualStudio.TextManager.Interop.WORDEXTFLAGS, Int32 ByRef, Int32 ByRef)
   at Microsoft.VisualStudio.Package.ViewFilter.GetWordExtent(Int32, Int32, UInt32, Microsoft.VisualStudio.TextManager.Interop.TextSpan[])
   at Microsoft.VisualStudio.Editor.Implementation.SimpleTextViewWindow.GetWordExtent(Int32, Int32, UInt32, Microsoft.VisualStudio.TextManager.Interop.TextSpan[])
   at Microsoft.VisualStudio.Editor.Implementation.ShimQuickInfoSource.TryGetQuickInfoFromDebugger(Microsoft.VisualStudio.Language.Intellisense.IQuickInfoSession, Microsoft.VisualStudio.TextManager.Interop.TextSpan[], System.String ByRef)
   at Microsoft.VisualStudio.Editor.Implementation.ShimQuickInfoSource.AugmentQuickInfoSession(Microsoft.VisualStudio.Language.Intellisense.IQuickInfoSession, System.Collections.Generic.IList`1<System.Object>, Microsoft.VisualStudio.Text.ITrackingSpan ByRef)
   at Microsoft.VisualStudio.Language.Intellisense.Implementation.QuickInfoSession.Recalculate()
   at Microsoft.VisualStudio.Language.Intellisense.Implementation.QuickInfoSession.Start()
   at Microsoft.VisualStudio.Editor.Implementation.ShimQuickInfoSource+<>c__DisplayClass12_0.<RetrySession>b__0(System.Object, System.EventArgs)
   at System.Windows.Threading.DispatcherTimer.FireTick(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)


```

**Comment by smoothdeveloper** [comment]
Changing title, doesn't seem to be directly related to FSI.

**Comment by cartermp** [comment]
Can you share the F# Script file?

**Comment by smoothdeveloper** [comment]
@cartermp I'm not able to reproduce it and I don't think it is related to the script itself, I'll try to find a way to reproduce. I'm hopping the stacktrace can help find something otherwise.

**Comment by cartermp** [comment]
Actually, it looks like this may be a dupe of #2318, except for some reason it's crashing on your machine.

The API crashing doesn't seem to be one that we own, but it could be due to us doing something funky.  Not sure what's up here :/

**Comment by smoothdeveloper** [comment]
You are right, the stack trace look similar up to `Microsoft.VisualStudio.Editor.Implementation.ShimQuickInfoSource+<>c__DisplayClass12_0.<RetrySession>b__0(System.Object, System.EventArgs)` here and `Microsoft.VisualStudio.Language.Intellisense.Implementation.DefaultQuickInfoController.OnTextView_MouseHover(Object sender, MouseHoverEventArgs e)` there.

![image](https://cloud.githubusercontent.com/assets/87944/22768117/1c63a254-ee80-11e6-9a19-b68a987c8dbc.png)

![image](https://cloud.githubusercontent.com/assets/87944/22768124/2ba68664-ee80-11e6-9499-6f317b4bd212.png)

**Comment by cartermp** [comment]
@smoothdeveloper Have you encountered this lately?

**Comment by smoothdeveloper** [comment]
Not seen again, I'm closing it.
