### ISSUE TITLE
Microsoft.VisualStudio.FSharp.Editor.FSharpDocumentDiagnosticAnalyze does not catch System.Threading.Tasks.TaskCanceledException

### ISSUE THREAD

**Issue by jmarolf** [Microsoft/visualfsharp#2768]
```
Warning	AD0001	Analyzer 'Microsoft.VisualStudio.FSharp.Editor.FSharpDocumentDiagnosticAnalyzer' threw an exception of type 'System.Threading.Tasks.TaskCanceledException' with message 'A task was canceled.'.	PerfStore		1	Active	Analyzer 'Microsoft.VisualStudio.FSharp.Editor.FSharpDocumentDiagnosticAnalyzer' threw the following exception:
'System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Diagnostics.EngineV2.DiagnosticIncrementalAnalyzer.Executor.<ComputeDocumentDiagnosticAnalyzerDiagnosticsAsync>d__12.MoveNext()
-----
'.
```

**Comment by vasily-kirichenko** [comment]
Duplication of https://github.com/Microsoft/visualfsharp/issues/2100
