### ISSUE TITLE
VSIXInstaller /quiet fails for F# nightly builds (from VS Community)

### ISSUE THREAD

**Issue by cartermp** [Microsoft/visualfsharp#2851]
Please provide a succinct description of the issue.

#### Repro steps

1. Install the Visual F# nightlies in quiet mode.

#### Expected behavior

It installsjust fine.

#### Actual behavior

Result: No UI, but this is the error

``` 4/9/2017 7:50:01 PM - The extension will be upgraded from version 15.4.1.17022502. 4/9/2017 7:50:03 PM - Uninstalling 'Visual F# Tools', version 15.4.1.17022502. 4/9/2017 7:50:05 PM - Install Error : System.InvalidOperationException: The VSIX's catalog does not include a 'Component' which is required for install/uninstall. at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.PerformSetupEngineUnInstall(IInstalledExtension extension) at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.UninstallInternal(IInstalledExtension extension, Boolean forceDelete, Version targetedVSVersion) at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.Uninstall(IInstalledExtension extension, Version targetedVSVersion) at VSIXInstaller.App.InstallSilently(IInstallableExtension extension, IReadOnlyList`1 installSKUs) ```

**Comment by cartermp** [comment]
This was reported by @ctaggart.  I cannot reproduce this right now on my machine, though.

**Comment by ctaggart** [comment]
@cartermp The bug is not while uninstalling, but while installing.

**Comment by cartermp** [comment]
Derp.  I'll repro when I get home tonight.

**Comment by ctaggart** [comment]
This can be reproduced with the script from #2829. You need to not have an FSharp daily installed.
```
git fetch origin pull/2829/head:pr2829
git checkout pr2829
.\scripts\Install-VisualFSharpNightly.ps1 -Quiet -Version '15.4.1.17040601'
```
The error will be in the log `%temp%\VisualFSharp-15.4.1.17040601.txt`.

You can also just run without `-Version` to get the latest.
```
.\scripts\Install-VisualFSharpNightly.ps1 -Quiet
```

**Comment by cartermp** [comment]
cc @brettfo

**Comment by ctaggart** [comment]
This continues to block me from installing the builds on AppVeyor and testing the builds on our large F# code bases at Tachyus or any of my open source projects.

**Comment by dsyme** [comment]
@brettfo Would appreciate your help when you have time to take a look at this

**Comment by brettfo** [comment]
Apologies for being late to the party here.

According to internal discussions (@KevinRansom was on these and I can add @cartermp and @dsyme if they like), the first install of a VSIX needs to be thought the Visual Studio Installer; only upgrades are supported through VSIXInstaller.exe.  I'm not in a position to currently check this, but does anybody that's hitting this see it on the upgrade case, or only on the initial install?

**Comment by ctaggart** [comment]
@brettfo, to reproduce, you just need a machine that has the stable version of Visual Studio installed with Visual F#. In my case, I have Visual Studio Professional 15.2 installed. The machine doesn't yet have an F# daily build. The VSIXInstaller, only when in -Quiet mode tries to uninstall the F# that ships with Visual Studio. I fails. When VSIXinstaller is run with a UI, it doesn't try to uninstall it. Why do the two behave differently? 

``` powershell
Invoke-WebRequest https://raw.githubusercontent.com/Microsoft/visualfsharp/master/scripts/Install-VisualFSharpNightly.ps1 -OutFile Install-VisualFSharpNightly.ps1

.\Install-VisualFSharpNightly.ps1 -Quiet
```

The log is saved to %temp%\VisualFSharp-15.4.1.17051202.txt
```
5/12/2017 12:20:55 PM - Microsoft VSIX Installer
5/12/2017 12:20:55 PM - -------------------------------------------
5/12/2017 12:20:55 PM - vsixinstaller.exe version:
5/12/2017 12:20:55 PM - 15.0.26430.4 built by: D15SVC
5/12/2017 12:20:55 PM - -------------------------------------------
5/12/2017 12:20:55 PM - Command line parameters:
5/12/2017 12:20:55 PM - C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\VSIXInstaller.exe,/logFile:C:\Users\camer\AppData\Local\Temp\VisualFSharp-15.4.1.17051202.txt,/appidinstallpath:C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\devenv.exe,/skuName:Professional,/skuVersion:15.0.26430.4,/appidname:Microsoft Visual Studio Professional 2017,/instanceIds:9c34071f,/quiet,C:\Users\camer\AppData\Local\Temp\VisualFSharp-15.4.1.17051202.vsix
5/12/2017 12:20:55 PM - -------------------------------------------
5/12/2017 12:20:55 PM - Microsoft VSIX Installer
5/12/2017 12:20:55 PM - -------------------------------------------
5/12/2017 12:20:55 PM - Failed to initialize settings for Isolated Shell C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\ManagementStudio\ssms.exe: Unable to find an entry point named '?' in DLL 'PkgdefMgmt.dll'.
5/12/2017 12:20:55 PM - Initializing Install...
5/12/2017 12:20:56 PM - Extension Details...
5/12/2017 12:20:56 PM - 	Identifier         : VisualFSharp
5/12/2017 12:20:56 PM - 	Name               : Visual F# Tools
5/12/2017 12:20:56 PM - 	Author             : Microsoft.VisualFSharpTools
5/12/2017 12:20:56 PM - 	Version            : 15.4.1.17051202
5/12/2017 12:20:56 PM - 	Description        : Deploy Visual F# Tools templates to Visual Studio
5/12/2017 12:20:56 PM - 	Locale             : en-US
5/12/2017 12:20:56 PM - 	MoreInfoURL        : https://docs.microsoft.com/en-us/dotnet/articles/fsharp/
5/12/2017 12:20:56 PM - 	InstalledByMSI     : False
5/12/2017 12:20:56 PM - 	SupportedFrameworkVersionRange : [4.6,)
5/12/2017 12:20:56 PM - 
5/12/2017 12:21:00 PM - 	SignatureState     : ValidSignature
5/12/2017 12:21:00 PM - 	SignedBy           : Microsoft Corporation
5/12/2017 12:21:00 PM - 	Certificate Info   : 
5/12/2017 12:21:00 PM - 		-------------------------------------------------------
5/12/2017 12:21:00 PM - 		[Subject]       : CN=Microsoft Corporation, OU=MOPR, OU=OPC, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
5/12/2017 12:21:00 PM - 		[Issuer]        : CN=Microsoft Code Signing PCA 2010, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
5/12/2017 12:21:00 PM - 		[Serial Number] : 330000017D015E4C2BE2BCF66900000000017D
5/12/2017 12:21:00 PM - 		[Not Before]    : 2/15/2017 8:10:16 PM
5/12/2017 12:21:00 PM - 		[Not After]     : 5/9/2018 9:10:16 PM
5/12/2017 12:21:00 PM - 		[Thumbprint]    : 69713C6FF47FADFF90C9465F7783E6E08232B28F
5/12/2017 12:21:00 PM - 
5/12/2017 12:21:00 PM - 	Supported Products : 
5/12/2017 12:21:00 PM - 		Microsoft.VisualStudio.Pro
5/12/2017 12:21:00 PM - 			Version : [15.0]
5/12/2017 12:21:00 PM - 
5/12/2017 12:21:00 PM - 	References         : 
5/12/2017 12:21:00 PM - 	Prerequisites      : 
5/12/2017 12:21:00 PM - 		-------------------------------------------------------
5/12/2017 12:21:00 PM - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
5/12/2017 12:21:00 PM - 		Name         : Visual Studio core editor
5/12/2017 12:21:00 PM - 		Version      : [15.0,16.0)
5/12/2017 12:21:00 PM - 
5/12/2017 12:21:00 PM - Signature Details...
5/12/2017 12:21:00 PM - 	Extension is signed with a valid signature.
5/12/2017 12:21:00 PM - 
5/12/2017 12:21:00 PM - Found installed product - Visual Studio Professional 2017
5/12/2017 12:21:00 PM - PKGDEF Information: Looking for master PkgDef file, Path: C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\master.pkgdef

5/12/2017 12:21:00 PM - PKGDEF Information: Creating PkgDefCacheNonVolatile
5/12/2017 12:21:00 PM - PKGDEF Information: Double-checking master pkgdef file
5/12/2017 12:21:00 PM - PKGDEF Information: PkgDefManagement initialized
5/12/2017 12:21:00 PM - PKGDEF Information: RootFolder, Path: C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\

5/12/2017 12:21:00 PM - PKGDEF Information: ShellFolder, Path: C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\

5/12/2017 12:21:00 PM - PKGDEF Information: PkgDefSearchPath, Path: C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\Extensions;C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\CommonExtensions;C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\devenv.admin.pkgdef

5/12/2017 12:21:00 PM - PKGDEF Information: ImageManifestSearchPath, Path: C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\Extensions;C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\CommonExtensions;C:\Users\camer\AppData\Local\Microsoft\VisualStudio\15.0_9c34071f\Extensions

5/12/2017 12:21:00 PM - PKGDEF Information: ApplicationExtensionsFolder, Path: C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\Extensions

5/12/2017 12:21:00 PM - PKGDEF Information: "ZeroImpact" = dword:0, "MergeRegistry" = dword:3
5/12/2017 12:21:00 PM - PKGDEF Information: Could not find ConfigurationChanged timestamp., PKGDEF: 80070002
5/12/2017 12:21:00 PM - PKGDEF Information: PkgDefCache flags, PKGDEF: 7001
5/12/2017 12:21:00 PM - PKGDEF Information: Could not find ConfigurationChanged timestamp., PKGDEF: 80070002
5/12/2017 12:21:00 PM - PKGDEF Information: PkgDef cache is current.
5/12/2017 12:21:00 PM - PKGDEF Information: PkgDefManagement startup complete
5/12/2017 12:21:01 PM - The extension will be upgraded from version 15.4.1.17032801.
5/12/2017 12:21:03 PM - Uninstalling 'Visual F# Tools', version 15.4.1.17032801.
5/12/2017 12:21:05 PM - Install Error : System.InvalidOperationException: The VSIX's catalog does not include a 'Component' which is required for install/uninstall.
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.PerformSetupEngineUnInstall(IInstalledExtension extension)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.UninstallInternal(IInstalledExtension extension, Boolean forceDelete, Version targetedVSVersion)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.Uninstall(IInstalledExtension extension, Version targetedVSVersion)
   at VSIXInstaller.App.InstallSilently(IInstallableExtension extension, IReadOnlyList`1 installSKUs)
5/12/2017 12:21:05 PM - System.InvalidOperationException: The VSIX's catalog does not include a 'Component' which is required for install/uninstall.
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.PerformSetupEngineUnInstall(IInstalledExtension extension)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.UninstallInternal(IInstalledExtension extension, Boolean forceDelete, Version targetedVSVersion)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.Uninstall(IInstalledExtension extension, Version targetedVSVersion)
   at VSIXInstaller.App.InstallSilently(IInstallableExtension extension, IReadOnlyList`1 installSKUs)
   at VSIXInstaller.App.OnStartup(StartupEventArgs e)
```

**Comment by brettfo** [comment]
I didn't realize `-Quiet` tries to uninstall first.  I'll forward your log file to the appropriate internal teams.

**Comment by cartermp** [comment]
Closing, as this has been fixed internally by the correct team.
