### ISSUE TITLE
Analyzer 'Microsoft.VisualStudio.FSharp.Editor.FSharpDocumentDiagnosticAnalyzer' threw an exception 

### ISSUE THREAD

**Issue by irium** [Microsoft/visualfsharp#2874]
I'm constantly see the following in VS 2017 "Error List" window (many lines of it):

```
Analyzer 'Microsoft.VisualStudio.FSharp.Editor.FSharpDocumentDiagnosticAnalyzer' threw an exception of type 'System.Threading.Tasks.TaskCanceledException' with message 'A task was canceled.'.	
Analyzer 'Microsoft.VisualStudio.FSharp.Editor.FSharpDocumentDiagnosticAnalyzer' threw the following exception:
'System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Diagnostics.EngineV2.DiagnosticIncrementalAnalyzer.Executor.<ComputeDocumentDiagnosticAnalyzerDiagnosticsAsync>d__12.MoveNext()
```
#### Related information 

* Repro : just after solution rebuild.
* Windows 10 Pro
* VFPT Nightly 15.4.1.17041802
* .NET 4.6 project
* VS 2017 Pro with latest updates

**Comment by saul** [comment]
Looking at this again now... it looks like we fixed it in 95% of cases but it's just whack-a-mole trying to figure out where we've gone wrong.

**Comment by cartermp** [comment]
Closing in favor of #2100, which I've re-opened.
