### ISSUE TITLE
Latest nightly build 15.4.1.17042501 crashes Visual Studio on load

### ISSUE THREAD

**Issue by saul** [Microsoft/visualfsharp#2917]
@KevinRansom can this be rolled back ASAP?

ActivityLog states:
```
LegacySitePackage failed for package [FSharpPackage]Source: 'Microsoft.VisualStudio.Composition' Description: Expected 1 export(s) with contract name "Microsoft.VisualStudio.FSharp.Editor.SettingsPersistence+ISettings" but found 0 after applying applicable constraints.
Microsoft.VisualStudio.Composition.CompositionFailedException: Expected 1 export(s) with contract name "Microsoft.VisualStudio.FSharp.Editor.SettingsPersistence+ISettings" but found 0 after applying applicable constraints.
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExports(ImportDefinition importDefinition)
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExports[T,TMetadataView](String contractName, ImportCardinality cardinality)
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExport[T,TMetadataView](String contractName)
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExport[T](String contractName)
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExport[T]()
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExportedValue[T]()
   at Microsoft.VisualStudio.ComponentModelHost.ComponentModel.GetService[T]()
   at Microsoft.VisualStudio.FSharp.Editor.FSharpPackage.Initialize()
   at Microsoft.VisualStudio.Shell.Package.Microsoft.VisualStudio.Shell.Interop.IVsPackage.SetSite(IServiceProvider sp)
```

So I cleared my ComponentModelCache, and now Visual Studio crashes when trying to load F# solutions :(

**Comment by majocha** [comment]
Is it after clearing cache or just after installing?
What would make it stop working out of sudden?

Can't reproduce it
![image](https://cloud.githubusercontent.com/assets/1760221/25390081/c75f170a-29d2-11e7-8baa-dec9b425286a.png)

**Comment by saul** [comment]
The crash is after clearing the cache. The error in the ActivityLog breaks the package loading. That occurred immediately after updating to this version.

**Comment by dsyme** [comment]
It's a shame the VS update manager doesn't let you rollback to a specific version you want to use

**Comment by saul** [comment]
Also can't reproduce this anymore :/ It's auto updated again and it's working fine.
