### ISSUE TITLE
FSharpRangeToTextSpan crash on GoTo All

### ISSUE THREAD

**Issue by ImaginaryDevelopment** [Microsoft/visualfsharp#3180]
Vs 2017 is crashing on go to all after typing a few letters

#### Repro steps

Have not been able to reproduce outside of my enterprise solution (12 projects) 6 C#, 5 F#, 1 .SqlProj
Only started since last VS update.

#### Expected behavior

A list of possible matches for what I typed comes up

#### Actual behavior

Visual studio crashes. without showing anything in the goto all box
![image](https://cloud.githubusercontent.com/assets/121276/26792868/cf05371e-49e9-11e7-9494-b6737768aa21.png)

#### Known workarounds

use find in all files instead of the Go To All item.

#### Related information 
Obtained by attaching VS to another instance of VS:

```
System.ArgumentOutOfRangeException occurred
  HResult=0x80131502
  Message=Specified argument was out of the range of valid values.
  Source=Microsoft.CodeAnalysis
  StackTrace:
   at Microsoft.CodeAnalysis.Text.TextSpan..ctor(Int32 start, Int32 length)
   at Microsoft.VisualStudio.FSharp.Editor.RoslynHelpers.FSharpRangeToTextSpan(SourceText sourceText, range range)
   at <StartupCode$FSharp-Editor>.$NavigateToSearchService.clo@198-37.GenerateNext(IEnumerable`1& next)
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.MoveNextImpl()
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.System-Collections-IEnumerator-MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at Microsoft.FSharp.Collections.SeqModule.ToArray[T](IEnumerable`1 source)
   at <StartupCode$FSharp-Editor>.$NavigateToSearchService.clo@195-35.Invoke(FSharpParseFileResults _arg3)
   at Microsoft.FSharp.Control.AsyncBuilderImpl.args@823-1.Invoke(a a)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Editor.Implementation.NavigateTo.NavigateToItemProvider.Searcher.<SearchAsyncWorker>d__12.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Editor.Implementation.NavigateTo.NavigateToItemProvider.Searcher.<SearchAsync>d__11.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Editor.Implementation.NavigateTo.NavigateToItemProvider.Searcher.<Search>d__10.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

* Windows 10
* Visual Studio 15.2 (26439.12) Release (.NET 4.6.01586)
* Visual F# Tools 15.4.1.17060502
Just updated Visual F# tools to the latest nightly and it persists.

**Comment by dsyme** [comment]
I think the simple solution is to catch this exception in ``FSharpRangeToTextSpan``

**Comment by cartermp** [comment]
Or perhaps [short-circuit out when `StartLine` is 0](https://github.com/Microsoft/visualfsharp/blob/master/vsintegration/src/FSharp.Editor/Common/RoslynHelpers.fs#L23), as I suspect this is what's returned when FCS cannot find something that matches.  Though I think it's a bit suspect that it was able to get this far and generate this kind of exception when Go to All doesn't have something to return...

**Comment by realvictorprm** [comment]
Some additional checks in the method simply have to be made.

**Comment by dsyme** [comment]
> Or perhaps short-circuit out when StartLine is 0, as I suspect this is what's returned when FCS cannot find something that matches. 

Yes

> Though I think it's a bit suspect that it was able to get this far and generate this kind of exception when Go to All doesn't have something to return...

Yes :)

**Comment by dsyme** [comment]
@ImaginaryDevelopment If possible try https://github.com/Microsoft/visualfsharp/pull/3181 and see if it cures your problem? thanks

**Comment by ImaginaryDevelopment** [comment]
I'm not self-compiling fsharp tools, is that needed to try that fix?

**Comment by cartermp** [comment]
@ImaginaryDevelopment Yes, it's needed to test it out.

**Comment by dsyme** [comment]
@cartermp I'm confident that the fix is stabilizing, but it would be absolutely fantastic to try it out.  Perhaps it's also needed to get the fix applied?

@ImaginaryDevelopment Alternatively you can provide us with a repro? which we can verify

thanks!
don

**Comment by ImaginaryDevelopment** [comment]
I tried to copy more and more files into another empty solution, but as far
as I went trying to avoid any actual work logic code, I could not get a
repro on a made-up solution.

**Comment by cartermp** [comment]
@ImaginaryDevelopment If you're up for it, you can get started fairly easily.  This is the workflow I use:

1. Install prerequisites from here: https://github.com/Microsoft/visualfsharp/blob/master/DEVGUIDE.md#developing-the-visual-f-ide-tools-windows-only
2. Open the VS Command Prompt in Administrator mode
3. `build vs`
4. `msbuild VisualFSharp.sln`
5. `.\VisualFSharp.sln`
6. Set `VisualFSharpOpenSource` as the startup project
7. f5 or ctrl-f5 (latter will definitely be faster) to launch a hive of VS
8. Open the project in the launched VS hive

**Comment by dsyme** [comment]
Closing as I am convinced this is fixed.  @cartermp Do we need @ImaginaryDevelopment to verify?

**Comment by cartermp** [comment]
It'd be great if you could verify the fix @ImaginaryDevelopment, but the code is now safe and won't crash in the manner described above so I think this is good to close.

**Comment by Thorium** [comment]
The constant throw new ArgumentOutOfRangeException("length") -catches are interfering debugging.
Could there be added a length-check to `FSharpRangeToTextSpan` to RoslynHelpers.cs
```csharp
return new TextSpan(num2, num - num2);
```
Should be rather like
```csharp
var length = num - num2;
return length >= 0 ? new TextSpan(num2, length) : null;
```
