### ISSUE TITLE
vsixinstaller /u:VisualFSharp removes VSIX from 15.2 (success) and 15.2 (failed)

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#3383]
1. How to remove the VSIX from 15.3, but not from 15.2?
2. Removing from 15.3 failed:

```
25-Jul-17 15:56:00 - Uninstalling 'Visual F# Tools', version 15.4.1.17070102.
25-Jul-17 15:56:03 - System.InvalidOperationException: Uninstall of Visual F# Tools failed. To uninstall this extension please uninstall all of the following components: F# language support
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.PerformSetupEngineUnInstall(IInstalledExtension extension, Boolean downgrade)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.UninstallInternal(IInstalledExtension extension, Boolean forceDelete, Version targetedVSVersion, Boolean downgrade)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.Uninstall(IInstalledExtension extension, Version targetedVSVersion)
   at VSIXInstaller.InstallProgressPage.UninstallVsix(String vsixId, SupportedVSSKU targetSku, IProgress`1 progress)
```

**Comment by dsyme** [comment]
Closing old issue
