### ISSUE TITLE
Cannot drag files inside folders

### ISSUE THREAD

**Issue by cmeeren** [Microsoft/visualfsharp#3550]
While it's possible to create folders in F# project, it's not possible to drag existing .fs files directly to the folder.

#### Repro steps

1. Create a new F# project (also assuming an .fs file is created inside this project)
2. Create a folder in the project
3. Try to drag an .fs file to the folder

#### Expected behavior

The .fs file is moved into the folder.

#### Actual behavior

While dragging, the mouse pointer changes to the "Unavailable" state as long as you're inside the same project, and nothing happens when you drop the file.

#### Known workarounds

It's possible to move an .fs file to another project and then back inside the original project to the correct folder.

Using VS 15.3.3, VF# nightlies.

**Comment by abelbraaksma** [comment]
Interestingly, you can Cut-Paste a file into another folder. This removes it from the original location, but adds it to the new location (i.e., in the folder) with the name "Copy of originalname.fs". Not the same bug, I know, but can be used as alternative workaround.

I actually thought that on earlier versions this summer the drag and drop was possible, but I can confirm that it isn't, it doesn't work for me either.

**Comment by saul** [comment]
This definitely used to work - as did Cut and Paste - I made sure all of these were fixed with my folders PR.

**Comment by pnobre** [comment]
Using visual studio 2017 15.6.0p1 and visual f# tools nightly 15.4.1.17120704 has a stranger behavior:
- After the steps described above, after moving the file it crashes with the following exception
=====================
08/12/2017 10:28:27
Recoverable
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: newMkDoc
   at Microsoft.Requires.FailRange(String parameterName, String message)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectNode.<>c__DisplayClass467_0.<<TransferItem>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.ProjectSystem.ProjectMultiThreadedService.ExecuteSynchronously(Func`1 asyncAction)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectNode.<>c__DisplayClass548_0.<HrInvoke>b__0()
   at Microsoft.VisualStudio.ProjectSystem.VS.HResult.<>c__DisplayClass36_0.<Invoke>b__0()
   at Microsoft.VisualStudio.ProjectSystem.VS.HResult.Invoke(Func`1 action, IServiceProvider vsShellServiceProvider, IProjectFaultHandlerService projectFaultHandlerService, UnconfiguredProject project)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.ProjectSystem.CommonProjectSystemTools.Rethrow(Exception ex)
   at Microsoft.VisualStudio.ProjectSystem.ProjectErrorReporting.<>c__DisplayClass6_0.<SubmitErrorReport>b__0()
   at Microsoft.VisualStudio.ProjectSystem.ExceptionFilter.<>c__DisplayClass2_0.<Guard>b__0()
   at GuardMethodClass.GuardMethod(Func`1 , Func`2 , Func`2 )
===================

- However, after Visual Studio is restarted, and the same project reopened, folders can be created and files moved to them without any problem.

**Comment by cartermp** [comment]
@pnobre You should not be using that nightly release channel with the Preview builds of Visual Studio 2017.  We have a [nightly preview release](https://dotnet.myget.org/F/fsharp-preview/vsix) if you wish to use them with Preview builds.

Does this same issue reproduce on either 15.5 RTW or 15.6 Preview 1 _without_ the *15.4.x* nightly build atop it?

**Comment by pnobre** [comment]
I wasn't being able to reproduce it as I was just trying the functionality inside Visual Studio. After grabbing master and running VisualFSharpFull project, I was able to reproduce and track the problem.

**Comment by cartermp** [comment]
Thanks @pnobre!
