### ISSUE TITLE
Visual Studio crash (FailFast) when using new style fsproj files

### ISSUE THREAD

**Issue by dhwed** [Microsoft/visualfsharp#3695]
I converted a couple of my project files over to the new fsproj format, and now I'm getting this crash every time I open Visual Studio:

```
Application: devenv.exe
Framework Version: v4.0.30319
Description: The application requested process termination through System.Environment.FailFast(string message).
Message: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.Editor.Implementation.Structure.AbstractStructureTaggerProvider`1.<ProduceTagsAsync>d__6.MoveNext()
Stack:
   at System.Environment.FailFast(System.String, System.Exception)
   at Microsoft.CodeAnalysis.FailFast.OnFatalException(System.Exception)
   at Microsoft.CodeAnalysis.ErrorReporting.FatalError.Report(System.Exception, System.Action`1<System.Exception>)
   at Microsoft.CodeAnalysis.ErrorReporting.FatalError.ReportUnlessCanceled(System.Exception)
   at Microsoft.CodeAnalysis.Editor.Implementation.Structure.AbstractStructureTaggerProvider`1+<ProduceTagsAsync>d__6[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext()
   at Microsoft.CodeAnalysis.Editor.Implementation.Structure.AbstractStructureTaggerProvider`1+<ProduceTagsAsync>d__6[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.InvokeMoveNext(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action, Boolean, System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task.FinishStageThree()
   at System.Threading.Tasks.Task`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].TrySetResult(System.__Canon)
   at System.Threading.Tasks.TaskCompletionSource`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].TrySetResult(System.__Canon)
   at Microsoft.VisualStudio.FSharp.Editor.RoslynHelpers+StartAsyncAsTask@112-3[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Exception)
   at Microsoft.FSharp.Control.CancellationTokenOps+StartWithContinuations@964-1.Invoke(System.Runtime.ExceptionServices.ExceptionDispatchInfo)
   at <StartupCode$FSharp-Core>.$Control.loop@124-51(Microsoft.FSharp.Control.Trampoline, Microsoft.FSharp.Core.FSharpFunc`2<Microsoft.FSharp.Core.Unit,Microsoft.FSharp.Control.FakeUnitValue>)
   at Microsoft.FSharp.Control.Trampoline.ExecuteAction(Microsoft.FSharp.Core.FSharpFunc`2<Microsoft.FSharp.Core.Unit,Microsoft.FSharp.Control.FakeUnitValue>)
   at Microsoft.FSharp.Control.TrampolineHolder.Protect(Microsoft.FSharp.Core.FSharpFunc`2<Microsoft.FSharp.Core.Unit,Microsoft.FSharp.Control.FakeUnitValue>)
   at Microsoft.FSharp.Control.TaskHelpers.continuation@1183[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](Boolean, Microsoft.FSharp.Control.AsyncParams`1<System.__Canon>, System.Threading.Tasks.Task`1<System.__Canon>)
   at Microsoft.FSharp.Control.TaskHelpers+continueWith@1194[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Threading.Tasks.Task`1<System.__Canon>)
   at System.Threading.Tasks.ContinuationTaskFromResultTask`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.Tasks.Task.ExecutionContextCallback(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean)
   at System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

I'm using a vsix compiled from the latest commit (d39cba7b0fe4247f05f4065927dc4868ec34cb6a), and this happens both on VS 15.3 and VS 15.4 preview 4.

**Comment by vasily-kirichenko** [comment]
I don’t think Visual F# Tools support new style projects (yet?)

**Comment by cartermp** [comment]
The tools in 15.3 and 15.4 do not have proper support for .NET Core SDK-based projects.  This is something targeted for 15.5, which there aren't public builds of yet.

That said, the stack trace there looks problematic, and we haven't seen that happen before.  BlockStructure was causing a nullreference exception in the Microsoft.CodeAnalysis layer in 15.3 and 15.4.  @KevinRansom @Pilchie for FYI

**Comment by dhwed** [comment]
I'm on 15.4 now, and I've realized that this happens only when opening VS with a file from the new style fsproj already open.  After VS successfully loads, these files can then be viewed without any issues.

I haven't been able to reproduce this on a simple test solution, so it may be something specific to my real-world solution - I'll test again and update this issue once the 15.5 preview starts up.

**Comment by dhwed** [comment]
This is still happening on VS 15.5 preview 1 with the vsix compiled from b714ecb83648de5d145c49c9939f02766c7280a8.

With the vsix included in VS 15.5 preview 1 there is no crash, but I don't get any semantic highlighting in the files in my new style fsproj (I do have working expand/collapse regions though).

**Comment by cartermp** [comment]
cc @KevinRansom

**Comment by cartermp** [comment]
@dhwed Can you provide a project or solution where you see this?  I just tested this with the [SAFE Bookstore](https://github.com/SAFE-Stack/SAFE-BookStore) and it loaded/restored packages and had features light up without issue.

**Comment by dhwed** [comment]
Looks like this is happening because I have a Common.props file so that things like the warning level can be defined in one place and then be consistent between all of my projects.

So, this can be reproduced with a `dotnet new console -lang F#` project with two minor modifications:

Add a new Common.props file with this content (my file actually has a `<PropertyGroup>`, but it isn't necessary to reproduce the crash):
```xml
<Project></Project>
```

and then add this line to the fsproj:
```xml
<Import Project="Common.props" />
```

Open the fsproj in VS, compile, then open the Project.fs file.  Then close and reopen VS, and it crashes.

**Comment by dhwed** [comment]
This isn't happening any more after @KevinRansom's p2p references work, so I'm going to close this.
