### ISSUE TITLE
Studio crashes when opening an F# source file using latest (> 15.4.1.17110202 ) build

### ISSUE THREAD

**Issue by mrichgml** [Microsoft/visualfsharp#3917]
When attempting to open an F# source file studio crashes instantly with a brief (too brief to read) error message.

The application event log contains the following:

Application: devenv.exe
Framework Version: v4.0.30319
Description: The application requested process termination through System.Environment.FailFast(string message).
Message: System.NullReferenceException: Object reference not set to an instance of an object.
at Microsoft.CodeAnalysis.Editor.Implementation.Structure.AbstractStructureTaggerProvider`1.<ProduceTagsAsync>d_6.MoveNext()
Stack:
at System.Environment.FailFast(System.String, System.Exception)
at Microsoft.CodeAnalysis.FailFast.OnFatalException(System.Exception)
at Microsoft.CodeAnalysis.ErrorReporting.FatalError.Report(System.Exception, System.Action`1<System.Exception>)
at Microsoft.CodeAnalysis.ErrorReporting.FatalError.ReportUnlessCanceled(System.Exception)
at Microsoft.CodeAnalysis.Editor.Implementation.Structure.AbstractStructureTaggerProvider`1+<ProduceTagsAsync>d6[[System.Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext()
at Microsoft.CodeAnalysis.Editor.Implementation.Structure.AbstractStructureTaggerProvider`1+<ProduceTagsAsync>d6[[System.Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext()
at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.InvokeMoveNext(System.Object)
at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()
at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action, Boolean, System.Threading.Tasks.Task ByRef)
at System.Threading.Tasks.Task.FinishContinuations()
at System.Threading.Tasks.Task.FinishStageThree()
at System.Threading.Tasks.Task`1[[System.Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].TrySetResult(System.Canon)
at System.Threading.Tasks.TaskCompletionSource`1[[System.Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].TrySetResult(System.Canon)
at Microsoft.VisualStudio.FSharp.Editor.RoslynHelpers+StartAsyncAsTask@112-3[[System._Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Exception)
at Microsoft.FSharp.Control.CancellationTokenOps+StartWithContinuations@964-1.Invoke(System.Runtime.ExceptionServices.ExceptionDispatchInfo)
at <StartupCode$FSharp-Core>.$Control.loop@124-51(Microsoft.FSharp.Control.Trampoline, Microsoft.FSharp.Core.FSharpFunc`2<Microsoft.FSharp.Core.Unit,Microsoft.FSharp.Control.FakeUnitValue>)
at Microsoft.FSharp.Control.Trampoline.ExecuteAction(Microsoft.FSharp.Core.FSharpFunc`2<Microsoft.FSharp.Core.Unit,Microsoft.FSharp.Control.FakeUnitValue>)
at Microsoft.FSharp.Control.TrampolineHolder.Protect(Microsoft.FSharp.Core.FSharpFunc`2<Microsoft.FSharp.Core.Unit,Microsoft.FSharp.Control.FakeUnitValue>)
at <StartupCode$FSharp-Core>.$Control+-ctor@200-1.Invoke(System.Object)
at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(System.Object)
at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
at System.Threading.ThreadPoolWorkQueue.Dispatch()
at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

#### Repro steps

Double-click an F# source file to open in editor

#### Expected behavior

Studio should not crash

#### Actual behavior

Studio crashes immediately

#### Known workarounds

After reverting to build 15.4.1.17110202 (the last I had that worked correctly) the problem has gone.

**Comment by vasily-kirichenko** [comment]
Do you use nightly releases? If so, there was a bug with wrong System.ImmutableCollections package version, it's fixed in master and will be available in the next nightly.

**Comment by mrichgml** [comment]
Yes I do. I'll close this issue in that case.

**Comment by cartermp** [comment]
@mrichgml FYI there is now an updated nightly - let us know if it works for you.

**Comment by mrichgml** [comment]
Yep, much better now thank you.
