### ISSUE TITLE
System.Exception: dotnet mergenupkg --source c:\kevinransom\visualfsharp\fcs\../Release/FSharp.Compiler.Service.16.0.3.nupkg --other FSharp.Compiler.Service.netstandard/bin/Release/FSharp.Compiler.Service.16.0.3.nupkg --framework netstandard1.6 failed

### ISSUE THREAD

**Issue by KevinRansom** [Microsoft/visualfsharp#3921]
@forki, @dsyme 

On a clean master branch I get this build error building fcs

I get a build error building with this command on Windows with no changes

I wonder what pre-requisite might I have missed

````
git clean -fxdq
.\fcs\build.cmd release non

 ....

Starting Target: Nuget.AddNetStd (==> Build.NetStd, NuGet.NetFx)
'C:\Users\kevinr\AppData\Local\dotnetcore\dotnet.exe mergenupkg --source c:\kevinransom\visualfsharp\fcs\../Release/FSharp.Compiler.Service.16.0.3.nupkg --other FSharp.Compiler.Service.netstandard/bin/Release/FSharp.Compiler.Service.16.0.3.nupkg --framework netstandard1.6
It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '1.0.0' was not found.
  - Check application dependencies and target a framework version installed at:
      \
  - Alternatively, install the framework version '1.0.0'.
Running build failed.
Error:
System.Exception: dotnet mergenupkg --source c:\kevinransom\visualfsharp\fcs\../Release/FSharp.Compiler.Service.16.0.3.nupkg --other FSharp.Compiler.Service.netstandard/bin/Release/FSharp.Compiler.Service.16.0.3.nupkg --framework netstandard1.6 failed
   at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1379.Invoke(String message)
   at FSI_0005.Build.runDotnet(String workingDir, String args) in c:\kevinransom\visualfsharp\fcs\build.fsx:line 30
   at FSI_0005.Build.clo@167-18.Invoke(Unit _arg9) in c:\kevinransom\visualfsharp\fcs\build.fsx:line 170
   at Fake.TargetHelper.runSingleTarget(TargetTemplate`1 target) in D:\code\FAKE\src\app\FakeLib\TargetHelper.fs:line 626

---------------------------------------------------------------------
Build Time Report
---------------------------------------------------------------------
Target            Duration
------            --------
Clean             00:00:00.0024213
Restore           00:00:54.1823293
Build.NetFx       00:02:31.7543289
Build.NetStd      00:02:25.0530192
NuGet.NetFx       00:00:02.6156789
Nuget.AddNetStd   Failure
Total:            00:05:54.4503390
---------------------------------------------------------------------
Status:           Failure
---------------------------------------------------------------------
---------------------------------------------------------------------
  1) System.Exception: dotnet mergenupkg --source c:\kevinransom\visualfsharp\fcs\../Release/FSharp.Compiler.Service.16.0.3.nupkg --other FSharp.Compiler.Service.netstandard/bin/Release/FSharp.Compiler.Service.16.0.3.nupkg --framework netstandard1.6 failed
   at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1379.Invoke(String message)
   at FSI_0005.Build.runDotnet(String workingDir, String args) in c:\kevinransom\visualfsharp\fcs\build.fsx:line 30
   at FSI_0005.Build.clo@167-18.Invoke(Unit _arg9) in c:\kevinransom\visualfsharp\fcs\build.fsx:line 170
   at Fake.TargetHelper.runSingleTarget(TargetTemplate`1 target) in D:\code\FAKE\src\app\FakeLib\TargetHelper.fs:line 626
---------------------------------------------------------------------
````

**Comment by KevinRansom** [comment]
Sorted.  It looks like it needs dotnet coreclr 1. something installed.
