### ISSUE TITLE
Assertion: IncrementalBuild object has already been disposed!

### ISSUE THREAD

**Issue by cartermp** [Microsoft/visualfsharp#4137]
On self-built VSIX, after opening VisualFSharp.sln and `CompletionProviderTests.fs`, I get the below assertion.  I took no action in the IDE.

```
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------
IncrementalBuild object has already been disposed!

   at Microsoft.FSharp.Compiler.IncrementalBuilder.assertNotDisposed()
   at Microsoft.FSharp.Compiler.IncrementalBuilder.DecrementUsageCount()
   at <StartupCode$FSharp-Compiler-Private>.$Service.-ctor@2339-122.Invoke(Tuple`3 tupledArg)
   at Internal.Utilities.Collections.AgedLookup`3.strongDiscard(Value x)
   at <StartupCode$FSharp-Compiler-Private>.$InternalCollections.clo@110-11.Invoke(Value x)
   at Microsoft.FSharp.Primitives.Basics.List.iter[T](FSharpFunc`2 f, FSharpList`1 x)
   at Microsoft.FSharp.Collections.ListModule.Iterate[T](FSharpFunc`2 action, FSharpList`1 list)
   at Internal.Utilities.Collections.AgedLookup`3.AssignWithStrength[d,e](d tok, FSharpList`1 newdata, FSharpList`1 discard1)
   at <StartupCode$FSharp-Compiler-Private>.$Service.clo@2350-426.Invoke(Tuple`3 _arg3)
   at Microsoft.FSharp.Compiler.AbstractIL.Internal.Library.CancellableModule.bind@711.Invoke(CancellationToken ct)
   at Microsoft.FSharp.Compiler.AbstractI......
<truncated>
---------------------------
Abort   Retry   Ignore   
---------------------------
```

Could this be related to #4121?

cc @dsyme @KevinRansom @dwed

**Comment by cartermp** [comment]
The IDE seems to work fine when I ignore this. Unfortunately, the stack trace in the assertion is kind of useless

**Comment by cartermp** [comment]
Related, after I was debugging CompletionProvider:

```
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------
   at Microsoft.FSharp.Compiler.CompileOps.TcImports.CheckDisposed()
   at Microsoft.FSharp.Compiler.CompileOps.TcImports.GetImportMap()
   at Microsoft.FSharp.Compiler.SourceCodeServices.Impl.cenv..ctor(TcGlobals g, CcuThunk thisCcu, TcImports tcImports)
   at Microsoft.FSharp.Compiler.SourceCodeServices.FSharpSymbol.Create(TcGlobals g, CcuThunk thisCcu, TcImports tcImports, Item item)
   at <StartupCode$FSharp-Compiler-Private>.$Service.GetSymbolUseAtLocation@1235.Invoke(Unit unitVar0)
   at Microsoft.FSharp.Compiler.SourceCodeServices.ErrorScope.Protect[a](range m, FSharpFunc`2 f, FSharpFunc`2 err)
   at Microsoft.FSharp.Compiler.SourceCodeServices.TypeCheckInfo.GetSymbolUseAtLocation(CompilationThreadToken ctok, Int32 line, String lineStr, Int32 colAtEndOfNames, FSharpList`1 names)
   at <StartupCode$FSharp-Compiler-Private>.$Service.GetSymbolUseAtLocation@1965-4.Invoke(CompilationThreadToken ctok, TypeCheckInfo scope)
   at <StartupCode$FSharp-Compiler-Private>.$Service.clo@1899-415.Invoke(CompilationThreadToken ctok)
   at <StartupCode$FSharp-Compiler-Private>.$Reactor.EnqueueAndAwaitOpAsync@174-2.Invoke(CompilationThreadToken ctok)
   at <StartupCode$FSharp-Compiler-Private>.$Reactor.loop@70-95.Invoke(FSharpOption`1 _arg2)
   at Microsoft.FSharp.Control.AsyncBuilderImpl.args@506-1.Invoke(a a)
   at <StartupCode$FSharp-Core>.$Control.loop@124-50(Trampoline this, FSharpFunc`2 action)
   at Microsoft.FSharp.Control.Trampoline.ExecuteAction(FSharpFunc`2 firstAction)
   at Microsoft.FSharp.Control.TrampolineHolder.Protect(FSharpFunc`2 firstAction)
   at <StartupCode$FSharp-Core>.$Control.AwaitWaitHandle@1326-2.Invoke(Object _arg5, Boolean timeOut)
   at System.Threading._ThreadPoolWaitOrTimerCallback.WaitOrTimerCallback_Context(Object state, Boolean timedOut)
   at System.Threading._ThreadPoolWaitOrTimerCallback.WaitOrTimerCallback_Context_t(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading._ThreadPoolWaitOrTimerCallback.PerformWaitOrTimerCallback(Object state, Boolean timedOut)
---------------------------
Abort   Retry   Ignore   
---------------------------

```

**Comment by cartermp** [comment]
I can't get this to repro reliably :(

**Comment by cartermp** [comment]
Okay, this is making it impossible to write code in the editor.  It seems to be hit by completion.

**Comment by cartermp** [comment]
Perhaps this is actually from here: https://github.com/Microsoft/visualfsharp/pull/4132, as it's this built-in VSIX where I get the assertion.  It does contai

**Comment by dhwed** [comment]
@cartermp I saw this debug assert a lot more before my changes in #4121, although that change did seem to make this assert less frequent.

**Comment by cartermp** [comment]
It could be due to 351d06b6c184e5fa4176e336ac7dff2b89047ec0, if you were working atop that.  But if not, then I definitely have no idea what could be causing this.

**Comment by dhwed** [comment]
I saw this assert at 518e59bef76ac382a175de7773c0f47e1cd75f88 last Friday, which was before your 351d06b6c184e5fa4176e336ac7dff2b89047ec0 restructuring.

**Comment by cartermp** [comment]
Closing as this was not reliable and I haven't seen it lately
