### ISSUE TITLE
wrong resource name in latest FCS

### ISSUE THREAD

**Issue by enricosada** [Microsoft/visualfsharp#4150]
in latest FCS .net standard built from sources, the resource name for `FSStrings` is wrong.

![image](https://user-images.githubusercontent.com/147243/34255134-81a7a6fc-e64f-11e7-99ec-1ee474ec1e0d.png)

is `FSharp.Compiler.Service.netstandard.FSStrings.resources`, instead of `FSStrings.resources`, that cause a runtime error:

```
Unhandled Exception: Unhandled Exception: Unhandled error - WrappedError(Could not find any resources appropriate for the specified culture or the neutral culture.  Make sure "fsstrings.resources" was correctly embedded or linked into assembly "FSharp.Compiler.Service" at compile time, or that all the satellite assemblies required are loadable and fully signed.) 
    at Microsoft.FSharp.Compiler.Lexhelp.reusingLexbufForParsing[a](LexBuffer`1 lexbuf, FSharpFunc`2 f)
   at Microsoft.FSharp.Compiler.SourceCodeServices.Parser.parseFile(String source, String fileName, FSharpParsingOptions options, String userOpName)
   at <StartupCode$FSharp-Compiler-Service>.$Service.ParseFile@2432.Invoke(Unit unitVar)
   at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@839.Invoke(AsyncParams`1 args)
System.AggregateException: One or more errors occurred. (WrappedError(Could not find any resources appropriate for the specified culture or the neutral culture.  Make sure "fsstrings.resources" was correctly embedded or linked into assembly "FSharp.Compiler.Service" at compile time, or that all the satellite assemblies required are loadable and fully signed.)) ---> Microsoft.FSharp.Compiler.ErrorLogger+WrappedError: WrappedError(Could not find any resources appropriate for the specified culture or the neutral culture.  Make sure "fsstrings.resources" was correctly embedded or linked into assembly "FSharp.Compiler.Service" at compile time, or that all the satellite assemblies required are loadable and fully signed.)
   at Microsoft.FSharp.Compiler.Lexhelp.reusingLexbufForParsing[a](LexBuffer`1 lexbuf, FSharpFunc`2 f)
   at Microsoft.FSharp.Compiler.SourceCodeServices.Parser.parseFile(String source, String fileName, FSharpParsingOptions options, String userOpName)
   at <StartupCode$FSharp-Compiler-Service>.$Service.ParseFile@2432.Invoke(Unit unitVar)
   at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@839.Invoke(AsyncParams`1 args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.FSharp.Control.AsyncBuilderImpl.commit[a](AsyncImplResult`1 res)
   at Microsoft.FSharp.Control.CancellationTokenOps.RunSynchronouslyInCurrentThread[a](CancellationToken token, FSharpAsync`1 computation)
   at Microsoft.FSharp.Control.CancellationTokenOps.RunSynchronously[a](CancellationToken token, FSharpAsync`1 computation, FSharpOption`1 timeout)
   at Microsoft.FSharp.Control.FSharpAsync.RunSynchronously[T](FSharpAsync`1 computation, FSharpOption`1 timeout, FSharpOption`1 cancellationToken)
   at <StartupCode$FsAutoComplete-Core>.$Commands.clo@90-13.Invoke(String file) in D:\Programowanie\ionide\paket-files\github.com\fsharp\FsAutoComplete\src\FsAutoComplete.Core\Commands.fs:line 104
   at Microsoft.FSharp.Collections.ArrayModule.Parallel.Iterate@1314.Invoke(Int32 obj)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.For(Int32 fromInclusive, Int32 toExclusive, Action`1 body)
   at Microsoft.FSharp.Collections.ArrayModule.Parallel.Iterate[T](FSharpFunc`2 action, T[] array)
   at <StartupCode$FsAutoComplete-Core>.$Commands.clo@88-12.Invoke(Unit unitVar) in D:\Programowanie\ionide\paket-files\github.com\fsharp\FsAutoComplete\src\FsAutoComplete.Core\Commands.fs:line 90
   at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@839.Invoke(AsyncParams`1 args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.FSharp.Control.CancellationTokenOps.Start@1292-1.Invoke(ExceptionDispatchInfo edi)
   at <StartupCode$FSharp-Core>.$Control.loop@425-51(Trampoline this, FSharpFunc`2 action)
   at Microsoft.FSharp.Control.Trampoline.ExecuteAction(FSharpFunc`2 firstAction)
   at <StartupCode$FSharp-Core>.$Control.-ctor@509-1.Invoke(Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
System.AggregateException: One or more errors occurred. (WrappedError(Could not find any resources appropriate for the specified culture or the neutral culture.  Make sure "fsstrings.resources" was correctly embedded or linked into assembly "FSharp.Compiler.Service" at compile time, or that all the satellite assemblies required are loadable and fully signed.)) ---> Microsoft.FSharp.Compiler.ErrorLogger+WrappedError: WrappedError(Could not find any resources appropriate for the specified culture or the neutral culture.  Make sure "fsstrings.resources" was correctly embedded or linked into assembly "FSharp.Compiler.Service" at compile time, or that all the satellite assemblies required are loadable and fully signed.)
   at Microsoft.FSharp.Compiler.Lexhelp.reusingLexbufForParsing[a](LexBuffer`1 lexbuf, FSharpFunc`2 f)
   at Microsoft.FSharp.Compiler.SourceCodeServices.Parser.parseFile(String source, String fileName, FSharpParsingOptions options, String userOpName)
   at <StartupCode$FSharp-Compiler-Service>.$Service.ParseFile@2432.Invoke(Unit unitVar)
   at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@839.Invoke(AsyncParams`1 args)
```

**Comment by enricosada** [comment]
Probably we should set the `LogicalName` in https://github.com/Microsoft/visualfsharp/blob/379da2367f5a9f155bfb60250a23d739d133117f/fcs/FSharp.Compiler.Service.netstandard/FSharp.Compiler.Service.netstandard.fsproj#L82-L84

Affect the `EmbeddedResource`, the `FsSrGen` like `FSIStrings` are ok.

because RootNamespace is not supported? (ref https://github.com/Microsoft/visualfsharp/issues/1051 )

**Comment by 7sharp9** [comment]
`RootNamespace` is fixed with opt in `useStandardResourceNames`

**Comment by enricosada** [comment]
that may expain why fails on .net standard (built by .net core sdk)

https://github.com/Microsoft/visualfsharp/blob/44fa027b308681a1b78a089e44fa1ab35ff77b41/src/fsharp/FSharp.Build/Microsoft.FSharp.NetSdk.props#L44

**Comment by 7sharp9** [comment]
I think this must have been broken since at least last year, Im testing with a 2016 build now, all the 2017 builds are not xplat for reading resources.  i.e. the root namespace will be present fin a win build but not a nix one, so null stream when reading.

**Comment by enricosada** [comment]
added PR #4151  to fix FCS meanwhile we find the root cause of this

**Comment by ncave** [comment]
@enricosada Thanks for the PR, I posted about this [issue](https://github.com/Microsoft/visualfsharp/pull/3784#issuecomment-347716596) a few weeks back but didn't take the next logical step of submitting a PR, sorry about that. My vague recollection seems to be it started happening around the change from 2.0.2 to 2.0.3, but I could be wrong.

**Comment by dsyme** [comment]
This was fixed by the above PR
