### ISSUE TITLE
Diffing fails from AnkhSVN

### ISSUE THREAD

**Issue by cmeeren** [Microsoft/visualfsharp#4507]
When viewing file changes from AnkhSVN, I get the following stack trace and no diff. This suddenly started happening after restarting VS, where VF# was updated to the latest nightly 180313019. Using VS15.6.

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.VisualStudio.FSharp.Editor.FSharpLanguageService.SetupNewTextView(IVsTextView textView)
   at Microsoft.VisualStudio.LanguageServices.Implementation.LanguageService.AbstractLanguageService`2.VsCodeWindowManager.AddAdornments()
   at Microsoft.VisualStudio.Editor.Implementation.CompoundTextViewWindow.TextDocData_OnNewLanguageService(Guid& sidLangServiceID)
   at Microsoft.VisualStudio.Editor.Implementation.CompoundTextViewWindow.OnPrimaryView_FullyInitialized()
   at Microsoft.VisualStudio.Editor.Implementation.CompoundTextViewWindow.PrimaryView_TextViewHostUpdated(Object sender, EventArgs e)
   at Microsoft.VisualStudio.Editor.Implementation.SimpleTextViewWindow.Init_InitializeWpfTextView()
   at Microsoft.VisualStudio.Editor.Implementation.SimpleTextViewWindow.Init_OnActivation()
   at Microsoft.VisualStudio.Editor.Implementation.SimpleTextViewWindow.get_WpfTextViewHost()
   at Microsoft.VisualStudio.Editor.Implementation.SimpleTextViewWindow.GetData(Guid& riidKey, Object& pvtData)
   at Microsoft.VisualStudio.Editor.Implementation.VsEditorAdaptersFactoryService.GetWpfTextViewHostFromVsTextView(IVsTextView viewAdapter)
   at Microsoft.VisualStudio.Editor.Implementation.VsEditorAdaptersFactoryService.GetWpfTextViewHost(IVsTextView viewAdapter)
   at Microsoft.VisualStudio.Differencing.Package.DiffViewerCodeWindow.<>c__DisplayClass29_0.<InitializeViewer>b__0(IDifferenceTextViewModel textViewModel, ITextViewRoleSet baseRoles, IEditorOptions options, FrameworkElement& visualElement, IWpfTextViewHost& textViewHost)
   at Microsoft.VisualStudio.Text.Differencing.Implementation.DifferenceViewer.Initialize(IDifferenceBuffer differenceBuffer, CreateTextViewHostCallback createTextViewHost, IEditorOptions parentOptions)
   at Microsoft.VisualStudio.Differencing.Package.DiffViewerCodeWindow.InitializeViewer()
   at Microsoft.VisualStudio.Differencing.Package.DiffPackage.DiffFiles(String leftFile, String rightFile, IVsWindowFrame& windowFrame, UInt32 options, String caption, String tooltip, String leftLabel, String rightLabel, String inlineLabel, String roles, Boolean packageIsLoading)
   at Microsoft.VisualStudio.Differencing.Package.DiffPackage.<>c__DisplayClass17_0.<OpenComparisonWindow2>b__0()
   at Microsoft.VisualStudio.Shell.ThreadHelper.Invoke[TResult](Func`1 method)
   at Microsoft.VisualStudio.Differencing.Package.DiffPackage.OpenComparisonWindow2(String leftFile, String rightFile, String caption, String tooltip, String leftLabel, String rightLabel, String inlineLabel, String roles, UInt32 options)
   at Ankh.VS.Services.InternalDiff.RunDiff(AnkhDiffArgs args)
   at Ankh.Services.AnkhDiff.RunDiff(AnkhDiffArgs args)
   at Ankh.Commands.DiffLocalItem.OnExecute(CommandEventArgs e)
   at Ankh.Commands.CommandMapItem.OnExecute(CommandEventArgs e)
   at Ankh.Commands.CommandMapper.Execute(AnkhCommand command, CommandEventArgs e)
```

**Comment by majocha** [comment]
Not sure if this is related but I glanced in Visual Studio release notes that 15.6.1 contains some fix for AnkhSVN.

**Comment by cmeeren** [comment]
Not related.

**Comment by cmeeren** [comment]
Uninstalling the nightlies fixed the problem, so this seems to be a change brought on by a recent nightly.

**Comment by cartermp** [comment]
The change which _could_ have brought this on is this: https://github.com/Microsoft/visualfsharp/blame/master/vsintegration/src/FSharp.Editor/LanguageService/LanguageService.fs#L580

Where outlining is enabled/disabled based on settings.

No idea which of the values in that method throws the exception, but it would seem very strange for things to be `null` there, given that these are all parts of the editor. If AnkhSVN is doing things strangely with the editor it could result in there being an issue where something can't be initialized (e.g., the `OutliningManager` on the `wpfTextView`).

Ooof this is a pain to reproduce. Is there a good free SVN hosting provider I can use for a test project?

**Comment by cmeeren** [comment]
Might not be SVN's fault. I tried viewing a diff in VS when using Git and I get the following message:

![image](https://user-images.githubusercontent.com/7766733/37431871-b9d50b50-27d6-11e8-9965-1ec9eb9085a9.png)

**Comment by cmeeren** [comment]
Note that the above error only happens with the nightlies. After uninstalling the nightlies, it works fine.

**Comment by cmeeren** [comment]
Also note that I don't know exactly which nightly introduced this error. I discovered it after updating to 18031301, but I might have skipped some nightlies.

**Comment by cartermp** [comment]
@cmeeren I believe I have fixed this with #4520. Below is with a VSIX built from that PR:

![fixed](https://user-images.githubusercontent.com/6309070/37433068-bae11a00-2797-11e8-8dfe-e4d3b2fbd9f0.gif)

On the latest nightly, I can reproduce the issue with the git viewer as you've mentioned.

If you have the time, I'd appreciate if you could test out the PR really quickly. If not, no worries 😄

**Comment by cmeeren** [comment]
Thanks! I'd rather wait for a new nightly after it's merged, I don't have a VF# dev environment for the time being and can't prioritize setting it up at the moment.

**Comment by cmeeren** [comment]
Thanks, works in 15.6.20180316.1.

**Comment by cartermp** [comment]
🎉 glad to hear it, @cmeeren
