### ISSUE TITLE
Warnings during build-from-VisualStudio

### ISSUE THREAD

**Issue by dsyme** [Microsoft/visualfsharp#4541]
We get lots of warnings and errors from a build of VisualFSharp.sln from Visual Studio.

@brettfo Would be great to get this clean.  Some are due to multi-proc build.

Errors:
```
1>FSharp.UIResources -> C:\GitHub\dsyme\visualfsharp\vsintegration\src\FSharp.UIResources\bin\Debug\FSharp.UIResources.dll
1>The system cannot find the path specified.
1>C:\GitHub\dsyme\visualfsharp\build\targets\ConvertPortablePdbs.targets(17,5): error MSB3073: The command ""C:\Users\dsyme\.nuget\packages\Microsoft.DiaSymReader.Pdb2Pdb\1.1.0-roslyn-62714-01\tools\Pdb2Pdb.exe" "C:\GitHub\dsyme\visualfsharp\vsintegration\src\FSharp.UIResources\bin\Debug\FSharp.UIResources.dll" /out "C:\GitHub\dsyme\visualfsharp\Debug\net40\bin\ConvertedPdbs\FSharp.UIResources.pdb" /verbose /srcsvrvar SRC_INDEX=public" exited with code 3.
1>Done building project "FSharp.UIResources.csproj" -- FAILED.
```
and
```
2>C:\GitHub\dsyme\visualfsharp\FSharp.Directory.Build.targets(32,5): error MSB3027: Could not copy "C:\GitHub\dsyme\visualfsharp\src\..\Debug\net40\bin\UnitTests\MockTypeProviders\FSharp.Core.dll" to "C:\GitHub\dsyme\visualfsharp\Debug\net40\bin\FSharp.Core.dll". Exceeded retry count of 10. Failed. 
2>C:\GitHub\dsyme\visualfsharp\FSharp.Directory.Build.targets(32,5): error MSB3021: Unable to copy file "C:\GitHub\dsyme\visualfsharp\src\..\Debug\net40\bin\UnitTests\MockTypeProviders\FSharp.Core.dll" to "C:\GitHub\dsyme\visualfsharp\Debug\net40\bin\FSharp.Core.dll". The requested operation cannot be performed on a file with a user-mapped section open.
2>C:\GitHub\dsyme\visualfsharp\FSharp.Directory.Build.targets(32,5): error MSB3021: 
```
and
```
21>------ Build started: Project: FSharp.Compiler.UnitTests, Configuration: Debug Any CPU ------
21>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(2052,5): warning MSB3277: Found conflicts between different versions of "System.ValueTuple" that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.
```
and
```
15>------ Build started: Project: FSharp.VS.FSI, Configuration: Debug Any CPU ------
15>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(4289,5): warning MSB3026: Could not copy "C:\GitHub\dsyme\visualfsharp\Debug\net40\bin\FSharp.Compiler.Private.pdb" to "bin\Debug\FSharp.Compiler.Private.pdb". Beginning retry 1 in 1000ms. The process cannot access the file 'C:\GitHub\dsyme\visualfsharp\Debug\net40\bin\FSharp.Compiler.Private.pdb' because it is being used by another process.
```
and
```
15>FSharp.VS.FSI -> C:\GitHub\dsyme\visualfsharp\vsintegration\src\FSharp.VS.FSI\bin\Debug\FSharp.VS.FSI.dll
15>C:\Users\dsyme\.nuget\packages\Microsoft.VSSDK.BuildTools\15.1.192\tools\vssdk\Microsoft.VsSDK.targets(979,5): error : CreatePkgDef : error : FileLoadException: Could not load file or assembly 'Microsoft.VisualStudio.Shell.Framework, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The process cannot access the file because it is being used by another process. (Exception from HRESULT: 0x80070020)
15>C:\Users\dsyme\.nuget\packages\Microsoft.VSSDK.BuildTools\15.1.192\tools\vssdk\Microsoft.VsSDK.targets(979,5): error :    at Microsoft.VisualStudio.Tools.CreatePkgDef.DoCreatePkgDef(InputArguments inputArguments)
15>C:\Users\dsyme\.nuget\packages\Microsoft.VSSDK.BuildTools\15.1.192\tools\vssdk\Microsoft.VsSDK.targets(979,5): error :    at Microsoft.VisualStudio.Tools.CreatePkgDef.Main(String[] arguments)
15>C:\Users\dsyme\.nuget\packages\Microsoft.VSSDK.BuildTools\15.1.192\tools\vssdk\Microsoft.VsSDK.targets(979,5): error : FileLoadException: Could not load file or assembly 'FSharp.Compiler.Private.dll' or one of its dependencies. The process cannot access the file because it is being used by another process. (Exception from HRESULT: 0x80070020)
15>C:\Users\dsyme\.nuget\packages\Microsoft.VSSDK.BuildTools\15.1.192\tools\vssdk\Microsoft.VsSDK.targets(979,5): error :    at System.Reflection.AssemblyName.nGetFileInformation(String s)
15>C:\Users\dsyme\.nuget\packages\Microsoft.VSSDK.BuildTools\15.1.192\tools\vssdk\Microsoft.VsSDK.targets(979,5): error :    at System.Reflection.AssemblyName.GetAssemblyName(String assemblyFile)
15>C:\Users\dsyme\.nuget\packages\Microsoft.VSSDK.BuildTools\15.1.192\tools\vssdk\Microsoft.VsSDK.targets(979,5): error :    at Microsoft.VisualStudio.Tools.CreatePkgDef.<AssemblyResolveHandler>g__LoadAssemblyIfItMatchesArgs7_0(String pathToAssembly, <>c__DisplayClass7_0& )
15>C:\Users\dsyme\.nuget\packages\Microsoft.VSSDK.BuildTools\15.1.192\tools\vssdk\Microsoft.VsSDK.targets(979,5): error :    at Microsoft.VisualStudio.Tools.CreatePkgDef.AssemblyResolveHandler(Object sender, ResolveEventArgs args)
15>C:\Users\dsyme\.nuget\packages\Microsoft.VSSDK.BuildTools\15.1.192\tools\vssdk\Microsoft.VsSDK.targets(979,5): error :    at System.AppDomain.OnAssemblyResolveEvent(RuntimeAssembly assembly, String assemblyFullName)
15>C:\Users\dsyme\.nuget\packages\Microsoft.VSSDK.BuildTools\15.1.192\tools\vssdk\Microsoft.VsSDK.targets(979,5): error : FileLoadException: The process cannot access the file because it is being used by another process. (Exception from HRESULT: 0x80070020)
15>C:\Users\dsyme\.nuget\packages\Microsoft.VSSDK.BuildTools\15.1.192\tools\vssdk\Microsoft.VsSDK.targets(979,5): error : 
15>C:\Users\dsyme\.nuget\packages\Microsoft.VSSDK.BuildTools\15.1.192\tools\vssdk\Microsoft.VsSDK.targets(979,5): error : 
15>C:\Users\dsyme\.nuget\packages\Microsoft.VSSDK.BuildTools\15.1.192\tools\vssdk\Microsoft.VsSDK.targets(979,5): error :
15>Done building project "FSharp.VS.FSI.fsproj" -- FAILED.
```
and
```
30>C:\Users\dsyme\.nuget\packages\xlifftasks\0.2.0-beta-000081\build\XliffTasks.targets(122,5): error : Two or more source files to be translated in the same project are named FSData.resx. Give them unique names or set unique XlfTranslatedFilename metadata.
```

Warnings:

```
1>AdvancedOptionsControl.xaml.cs(23,16,23,38): warning CS1591: Missing XML comment for publicly visible type or member 'AdvancedOptionsControl.AdvancedOptionsControl()'
1>IntegerRangeValidationRule.cs(8,18,8,44): warning CS1591: Missing XML comment for publicly visible type or member 'IntegerRangeValidationRule'
1>IntegerRangeValidationRule.cs(10,16,10,42): warning CS1591: Missing XML comment for publicly visible type or member 'IntegerRangeValidationRule.IntegerRangeValidationRule()'
1>IntegerRangeValidationRule.cs(15,20,15,23): warning CS1591: Missing XML comment for publicly visible type or member 'IntegerRangeValidationRule.Min'
1>IntegerRangeValidationRule.cs(17,20,17,23): warning CS1591: Missing XML comment for publicly visible type or member 'IntegerRangeValidationRule.Max'
1>IntegerRangeValidationRule.cs(19,42,19,50): warning CS1591: Missing XML comment for publicly visible type or member 'IntegerRangeValidationRule.Validate(object, CultureInfo)'
```
and
```
26>------ Build started: Project: FSharp.LanguageService, Configuration: Debug Any CPU ------
26>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(2052,5): warning MSB3277: Found conflicts between different versions of "Microsoft.Build" that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.
26>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(2052,5): warning MSB3277: Found conflicts between different versions of "Microsoft.DiaSymReader" that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.
26>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(2052,5): warning MSB3277: Found conflicts between different versions of "Microsoft.Build.Tasks.Core" that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.
26>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(2052,5): warning MSB3277: Found conflicts between different versions of "Microsoft.Build.Framework" that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.
26>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(2052,5): warning MSB3277: Found conflicts between different versions of "Microsoft.VisualStudio.Threading" that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.
```

**Comment by brettfo** [comment]
For the first issue you'll need to re-run `build.cmd vs`, possibly after a clean.

The missing XML comment warnings we've had for a long time and to be honest I've forgotten about them.  I'll add a `<NoWarn>` entry to turn that off.

The differing versions of `Microsoft.Build`, etc. are ultimate due to some of our projects being SDK-based and some not; this is something I'm actively working on cleaning up.

The locked files are something I haven't seen on my end, but obviously need to be fixed.  Do you (or @KevinRansom) have suggestions for making this process more smooth?

**Comment by dsyme** [comment]
@brettfo BTW I see this at the start of the build in the package manager output

    Error occurred while restoring NuGet packages: '$(XliffTasksPackageVersion)' is not a valid version string.

**Comment by brettfo** [comment]
That's coming from the property pages project and is a known issue with `msvbproj.dll`; the NuGet UI doesn't evaluate MSBuild properties.  I spoke with @Pilchie about this recently and from what I gathered it's a harmless (but annoying) issue in the IDE when using `<PackageReference>` nodes in non-SDK VB projects.

**Comment by dsyme** [comment]
OK, the current problems I see are:

1. You need to `build vs debug test` before or else you get errors like this:

       43>------ Build started: Project: VisualFSharp.UnitTests, Configuration: Debug Any CPU ------
       43>C:\Program Files\dotnet\sdk\2.1.100\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets(327,5): error : Assets file 'C:\GitHub\dsyme\visualfsharp\vsintegration\tests\unittests\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.
       43>C:\Program Files\dotnet\sdk\2.1.100\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets(167,5): error : Assets file 'C:\GitHub\dsyme\visualfsharp\vsintegration\tests\unittests\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.

   I suppose we should restore those test projects.

2. Rebuilding always rebuilds `FSharp.Editor.dll` because of this:

```
Target "GenerateAssemblyInfo" in file "C:\Program Files\dotnet\sdk\2.1.100\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.GenerateAssemblyInfo.targets" from project "C:\GitHub\dsyme\visualfsharp\vsintegration\src\FSharp.Editor\FSharp.Editor.fsproj" (target "CoreCompile" depends on it):
Done building target "GenerateAssemblyInfo" in project "FSharp.Editor.fsproj".
Target "CoreCompile" in file "C:\GitHub\dsyme\visualfsharp\Proto\net40\bin\Microsoft.FSharp.Targets" from project "C:\GitHub\dsyme\visualfsharp\vsintegration\src\FSharp.Editor\FSharp.Editor.fsproj" (target "Compile" depends on it):
Building target "CoreCompile" completely.
Input file "obj\debug\FSharp.Editor.resources" is newer than output file "obj\debug\FSharp.Editor.xml".
```

   It looks to me like the ``HACK_CopyOutputsToTheProperLocation`` is always copying that file across?  But why is it copying from `debug\net40\obj\` to `debug\net40\obj\`?


```
  Copying file from "obj\debug\FSharp.Editor.resources" to "C:\GitHub\dsyme\visualfsharp\debug\net40\obj\FSharp.Editor.resources".
```


3. I get this

```
14>ProjectSystem.Base -> C:\GitHub\dsyme\visualfsharp\vsintegration\src\FSharp.ProjectSystem.Base\Project\bin\Debug\FSharp.ProjectSystem.Base.dll
14>C:\GitHub\dsyme\visualfsharp\packages\Microsoft.VSSDK.BuildTools\15.1.192\tools\vssdk\Microsoft.VsSDK.targets(979,5): error : CreatePkgDef : error : ProvideEditorFactoryAttribute: Could not load file or assembly 'Microsoft.VisualStudio.Shell.15.0, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The process cannot access the file because it is being used by another process. (Exception from HRESULT: 0x80070020)
14>C:\GitHub\dsyme\visualfsharp\packages\Microsoft.VSSDK.BuildTools\15.1.192\tools\vssdk\Microsoft.VsSDK.targets(979,5): error :
```

4. I get this:

```
14>ProjectSystem.Base -> C:\GitHub\dsyme\visualfsharp\vsintegration\src\FSharp.ProjectSystem.Base\Project\bin\Debug\FSharp.ProjectSystem.Base.dll
15>LanguageServiceProfiling -> C:\GitHub\dsyme\visualfsharp\vsintegration\Utils\LanguageServiceProfiling\bin\Debug\LanguageServiceProfiling.exe
14>C:\GitHub\dsyme\visualfsharp\packages\Microsoft.VSSDK.BuildTools\15.1.192\tools\vssdk\Microsoft.VsSDK.targets(979,5): error : CreatePkgDef : error : FileLoadException: Could not load file or assembly 'Microsoft.VisualStudio.Shell.Framework, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The process cannot access the file because it is being used by another process. (Exception from HRESULT: 0x80070020)
14>C:\GitHub\dsyme\visualfsharp\packages\Microsoft.VSSDK.BuildTools\15.1.192\tools\vssdk\Microsoft.VsSDK.targets(979,5): error :    at Microsoft.VisualStudio.Tools.CreatePkgDef.DoCreatePkgDef(InputArguments inputArguments)
14>C:\GitHub\dsyme\visualfsharp\packages\Microsoft.VSSDK.BuildTools\15.1.192\tools\vssdk\Microsoft.VsSDK.targets(979,5): error :    at Microsoft.VisualStudio.Tools.CreatePkgDef.Main(String[] arguments)
14>C:\GitHub\dsyme\visualfsharp\packages\Microsoft.VSSDK.BuildTools\15.1.192\tools\vssdk\Microsoft.VsSDK.targets(979,5): error : FileLoadException: Could not load file or assembly 'FSharp.Compiler.Private.dll' or one of its dependencies. The process cannot access the file because it is being used by another process. (Exception from HRESULT: 0x80070020)
14>C:\GitHub\dsyme\visualfsharp\packages\Microsoft.VSSDK.BuildTools\15.1.192\tools\vssdk\Microsoft.VsSDK.targets(979,5): error :    at System.Reflection.AssemblyName.nGetFileInformation(String s)
14>C:\GitHub\dsyme\visualfsharp\packages\Microsoft.VSSDK.BuildTools\15.1.192\tools\vssdk\Microsoft.VsSDK.targets(979,5): error :    at System.Reflection.AssemblyName.GetAssemblyName(String assemblyFile)
14>C:\GitHub\dsyme\visualfsharp\packages\Microsoft.VSSDK.BuildTools\15.1.192\tools\vssdk\Microsoft.VsSDK.targets(979,5): error :    at Microsoft.VisualStudio.Tools.CreatePkgDef.<AssemblyResolveHandler>g__LoadAssemblyIfItMatchesArgs7_0(String pathToAssembly, <>c__DisplayClass7_0& )
14>C:\GitHub\dsyme\visualfsharp\packages\Microsoft.VSSDK.BuildTools\15.1.192\tools\vssdk\Microsoft.VsSDK.targets(979,5): error :    at Microsoft.VisualStudio.Tools.CreatePkgDef.AssemblyResolveHandler(Object sender, ResolveEventArgs args)
14>C:\GitHub\dsyme\visualfsharp\packages\Microsoft.VSSDK.BuildTools\15.1.192\tools\vssdk\Microsoft.VsSDK.targets(979,5): error :    at System.AppDomain.OnAssemblyResolveEvent(RuntimeAssembly assembly, String assemblyFullName)
14>C:\GitHub\dsyme\visualfsharp\packages\Microsoft.VSSDK.BuildTools\15.1.192\tools\vssdk\Microsoft.VsSDK.targets(979,5): error : FileLoadException: The process cannot access the file because it is being used by another process. (Exception from HRESULT: 0x80070020)
```

5.  I get this

```
22>------ Build started: Project: VisualFSharp.UnitTests, Configuration: Debug Any CPU ------
22>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(2052,5): warning MSB3277: Found conflicts between different versions of "Microsoft.DiaSymReader" that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.
22>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(2052,5): warning MSB3277: Found conflicts between different versions of "Microsoft.VisualStudio.Threading" that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.
22>C:\GitHub\dsyme\visualfsharp\packages\xlifftasks\0.2.0-beta-000081\build\XliffTasks.targets(122,5): error : Two or more source files to be translated in the same project are named FSData.resx. Give them unique names or set unique XlfTranslatedFilename metadata.
22>Done building project "VisualFSharp.UnitTests.fsproj" -- FAILED.
```

**Comment by brettfo** [comment]
1.  Good idea, I'll look into restoring those even if they're not getting executed.
2.  That copy is coming **from** a path relative to the `.fsproj` **to** the absolute path; those directories are expected.  As for `FSharp.Editor.resources` triggering it, that appears to be related to the XliffTasks package which handles our localized resources.  I'll have to dig in more.
3.  I'm not sure how a file from a NuGet package would get locked or why it would matter (shouldn't it be opened as read-only?)
4.  Same as 3.
5.  Those are expected due to the versions that we reference in our assemblies and newer versions that ultimately come from the Roslyn references.  These can't be upgraded until we move off of `project.json` and onto SDK projects for everything under `src\fsharp`, but that's what I'm actively working on.

**Comment by dsyme** [comment]
On (4) the file `C:\GitHub\dsyme\visualfsharp\vsintegration\tests\unittests\obj\Debug\VisualFSharp.UnitTests.xlf\XlfSources.txt` contains two entries:

```
MockTypeProviders\DummyProviderForLanguageServiceTesting\obj\Debug\net40\FSData.resx
MockTypeProviders\DummyProviderForLanguageServiceTesting\obj\net40\FSData.resx
```

**Comment by dsyme** [comment]
(2) is frustrating as it means we get repeated builds once more even when nothing changes.  That changes the turnaround time to 2 minutes or so, instead of a few seconds.  I'd appreciate you prioritizing that one as we keep regressing that.

(4) is really weird. DummyProviderForLanguageServiceTesting isn't even referenced by VisualFSharp.UnitTests and the thing seems to be some completely whacky artifact of the fact that DummyProviderForLanguageServiceTesting disables localization and happens to have been built just before VisualFSharp.UnitTests, so the "potential localization" is left lying around and collected into the build of VisualFSharp.UnitTests.  I suppose it's just some bug in XLF stuff but it's crazy.

(3) I don't know about.  It seems maybe to be something taking a lock on `FSharp.Compiler.Private.dll`

**Comment by dsyme** [comment]
@brettfo Trying to get a working VisualFSharp.sln of some kind but it is totally kafkaesque....

* OK, we need to to `build vs` beforehand.  If that doesn't build the test projects, we get error (1) above when using VisualFSharp.sln

* OK, so `build vs` builds the test projects.  But then it fails with error (4) because Xlf has some bizzaro bug

* OK, so we could make it that VisualFSharp.sln just doesn't have the test projects, or the test helpers.  But we don't really want that as we then can't unit tests from inside VisualFSharp.sln....

* And each iteration of testing this takes about 3-4 minutes because of bug (2).... Which will also make VisualFSharp.sln much less useful.  And I can't for the life of me work out what's going on with (2) - why on earth does "GenerateResources" not realise that everything is up to date? And why doesn't it tell is what's going on?

**Comment by dsyme** [comment]
@brettfo OK, solved (4) - we need

    <EnableDefaultEmbeddedResourceItems>false</EnableDefaultEmbeddedResourceItems>

in VisualFSharp.UnitTests.fsproj because the default algorithm was somehow looking into subdirectory DummyProviderForLanguageServiceTesting even though there is no project reference to the project.  Perhaps new style SDK projects just assume there are no projects nested in subdirectories of other projects.

**Comment by dsyme** [comment]
Kafka's back:

```
Error occurred while restoring NuGet packages: '$(XliffTasksPackageVersion)' is not a valid version string.
1>------ Build started: Project: FSharp.UIResources, Configuration: debug Any CPU ------
1>C:\WINDOWS\Microsoft.NET\Framework\v4.0.30319\Microsoft.WinFx.targets(419,45): error MSB4057: The target "CoreCompile" does not exist in the project.
1>Done building project "hznfmpwl.tmp_proj" -- FAILED.
```

Wat on earth? `hznfmpwl.tmp_proj`?  Which tool is generating project files on the fly?

**Comment by dsyme** [comment]
@brettfo Fixes here: https://github.com/Microsoft/visualfsharp/pull/4555

We only now need to solve the rebuild of FSharp.Editor.dll and other vsintegration DLLs.  It would also be nice if you didn't have to do `build vs` before starting.

**Comment by Pilchie** [comment]
> Wat on earth? hznfmpwl.tmp_proj? Which tool is generating project files on the fly and then failing to build them!????

Usually `tmp_proj` is WPF.

**Comment by dsyme** [comment]
@Pilchie Thanks :)

**Comment by dsyme** [comment]
@brettfo The lack of a working F5 is really biting me and making it very hard to work on #4586.  Can we get this fixed? I've tried 10 times to launch F5 but get project build failures every time after a 2 minute wait to rebuild FSharp.Editor etc.

Here's the latest error:

```
Error occurred while restoring NuGet packages: '$(XliffTasksPackageVersion)' is not a valid version string.
1>------ Build started: Project: FSharp.UIResources, Configuration: Debug Any CPU ------
1>C:\WINDOWS\Microsoft.NET\Framework\v4.0.30319\Microsoft.WinFx.targets(419,45): error MSB4057: The target "CoreCompile" does not exist in the project.
1>Done building project "4szbetr4.tmp_proj" -- FAILED.
...
========== Build: 16 succeeded, 1 failed, 5 up-to-date, 0 skipped ==========
```

**Comment by brettfo** [comment]
What version of VS do you have installed?  On 15.6.3 (released today) against clean master I'm able to F5 without FSharp.Editor rebuilding.

The `$(XliffTasksPackageVersion)` error is benign and comes from incomplete `<PackageReference>` support in `msvbproj.dll`, but that shouldn't affect F5, so it looks like the real issue is the `tmp_proj` issue, which is WPF.

Can you do a clean and rebuild?

**Comment by dsyme** [comment]
@brettfo 15.6.0.  I'll update and try again on both master and my branch

**Comment by dsyme** [comment]
@brettfo I can now F5 launch, that's great. However 

1. I'm definitely still seeing repeated builds of FSharp.Editor.dll and other things, see [this log](https://gist.github.com/dsyme/93d9991f3c108eb73c4e979528c47bf8).  To see that, just repeatedly build `VisualFSharp.sln` or repeatedly run 

       .\build vs

2. When I launch the debugger is **achingly** slow.  I don't know what's happened but it's almost impossible to do anything in the launched Visual Studio instance.  I can't tell if it's 
* a regression in general debug performance
* a regression in debug performance for F# code
* something specific to debugging devenv.exe instances
* or something specific to debugging launched instances of VisualFSharp.sln

**Comment by dsyme** [comment]
@brettfo Now I'm seeing this when using the package:

![image](https://user-images.githubusercontent.com/7204669/37688950-5bbd822c-2c9a-11e8-96ac-a3cb2ea5c09f.png)

**Comment by cartermp** [comment]
@dsyme Is IntelliTrace turned on perhaps?

**Comment by dsyme** [comment]
@cartermp Yes, I'll try without.

**Comment by cartermp** [comment]
@dsyme With the work to get SVT references done properly, you shouldn't see that. If that's the only remaining issue you can see, then let's close this as we have a different bug for debugging performance when IntelliTrace is active (which you should definitely always have off with F#)
