### ISSUE TITLE
Renaming file in .NET Standard project results in non-fatal error

### ISSUE THREAD

**Issue by cartermp** [Microsoft/visualfsharp#4624]
1. Create a new .NET Standard library
2. Replace the code with this:

```fsharp
namespace ValuesService

type IValuesService =
    abstract member GetAllValues: unit -> string[]
    abstract member TryGetValue: index: int -> Option<string>

type ValuesService() =
    let values = [|"value1"; "value2"|]

    interface IValuesService with
        member this.GetAllValues() = values

        member this.TryGetValue (index) =
            values
            |> Array.tryItem index
```

3. Rename `Library1.fs` to `Values.fs`

<img width="443" alt="screen shot 2018-03-26 at 9 54 28 am" src="https://user-images.githubusercontent.com/6309070/37910589-e70ae32a-30db-11e8-9ec6-9464f908fad4.png">

**Environment:**

* 15.6.4
* Parallels on Mac

**Comment by cartermp** [comment]
Stack trace from log:

```
=====================
3/26/2018 9:54:17 AM
Recoverable
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: newMkDoc
   at Microsoft.Requires.FailRange(String parameterName, String message)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectNode.<>c__DisplayClass473_0.<<TransferItem>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.ProjectSystem.ProjectMultiThreadedService.ExecuteSynchronously(Func`1 asyncAction)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectNode.<>c__DisplayClass554_0.<HrInvoke>b__0()
   at Microsoft.VisualStudio.ProjectSystem.VS.HResult.<>c__DisplayClass37_0.<Invoke>b__0()
   at Microsoft.VisualStudio.ProjectSystem.VS.HResult.Invoke(Func`1 action, IServiceProvider vsShellServiceProvider, IProjectFaultHandlerService projectFaultHandlerService, UnconfiguredProject project)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.ProjectSystem.CommonProjectSystemTools.Rethrow(Exception ex)
   at Microsoft.VisualStudio.ProjectSystem.ProjectErrorReporting.<>c__DisplayClass6_0.<SubmitErrorReport>b__0()
   at Microsoft.VisualStudio.ProjectSystem.ExceptionFilter.<>c__DisplayClass2_0.<Guard>b__0()
   at GuardMethodClass.GuardMethod(Func`1 , Func`2 , Func`2 )
===================
```

**Comment by cartermp** [comment]
Why is it calling the legacy project system for this?

**Comment by cartermp** [comment]
cc @TIHan

**Comment by TIHan** [comment]
I'm unable to reproduce this issue on 15.7 Preview 3.0 [27521.0.d15.7]. Can you try out the preview?

Also, it's not calling the legacy project system, that's CPS.

**Comment by cartermp** [comment]
I was having trouble reproducing it as well, and on stage it worked 😄 

I'll close this and re-open if it still repros on 15.7 Preview 3
