### ISSUE TITLE
Exceptions aren't handled in UnusedOpens

### ISSUE THREAD

**Issue by auduchinok** [Microsoft/visualfsharp#4664]
```
One or more errors occurred. The exception has been reported.
  This internal exception should now be caught at an error recovery point on the stack. Original message:
  A namespace and a module named 'JetBrains.ReSharper.Plugins.FSharp.Daemon.Stages' both occur in two parts of this assembly)

--- EXCEPTION #1/3 [ReportedError]
ExceptionPath.1 = Root.InnerException.InnerException
ExceptionPath.2 = Root.InnerException.InnerExceptions.#0
ClassName = Microsoft.FSharp.Compiler.ErrorLogger+ReportedError
HResult = COR_E_EXCEPTION=80131500
Source = FSharp.Compiler.Service
StackTraceString = “
  at Microsoft.FSharp.Compiler.ErrorLogger.ErrorLoggerExtensions.ErrorLogger.Error[b](ErrorLogger x, Exception exn)
     at Microsoft.FSharp.Compiler.ErrorLogger.error[a](Exception exn)
     at Microsoft.FSharp.Compiler.Tast.CombineModuleOrNamespaceTypes@5207.Invoke(FSharpList`1 path, range m, ModuleOrNamespaceType mty1, ModuleOrNamespaceType mty2)
     at System.Lazy`1.CreateValue()
     at System.Lazy`1.LazyInitValue()
     at Microsoft.FSharp.Compiler.Tast.Entity.get_IsNamespace()
     at Microsoft.FSharp.Compiler.SourceCodeServices.UnusedOpens.newlyUsedOpenedGroups@108-2.Invoke(FSharpSymbolUse symbolUse)
     at Microsoft.FSharp.Collections.ArrayModule.Exists[T](FSharpFunc`2 predicate, T[] array)
     at Microsoft.FSharp.Primitives.Basics.List.exists[T](FSharpFunc`2 predicate, FSharpList`1 xs1)
     at Microsoft.FSharp.Primitives.Basics.List.filter[T](FSharpFunc`2 predicate, FSharpList`1 l)
     at Microsoft.FSharp.Compiler.SourceCodeServices.UnusedOpens.getUsedModules(FSharpSymbolUse[] symbolUses, FSharpList`1 usedModules, OpenStatement openStatement)
     at Microsoft.FSharp.Compiler.SourceCodeServices.UnusedOpens.filterOpenStatementsIncremental@137.Invoke(Unit unitVar)
     at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@522.Invoke(AsyncParams`1 args)
”
```

**Comment by auduchinok** [comment]
@dsyme I think the biggest problem here is not the fact `UnusedOpens` throws an exception but that code that could be used by an FCS client (`FSharpEntity.IsNamespace`) throws it.
Regarding this particular exception: I'd expect `IsNamespace` to return value according to a file where that namespace/module was initially introduced.
