### ISSUE TITLE
Compile error: "primDestForallTy: not a forall type"

### ISSUE THREAD

**Issue by theprash** [Microsoft/visualfsharp#4670]
Referring to a function from the [Fable.Recharts](https://www.nuget.org/packages/Fable.Recharts/) library causes an unusual compile error.

#### Repro steps

Open and build [this solution](https://github.com/Microsoft/visualfsharp/files/1871846/vs2017-recharts.zip).

#### Expected behavior

A successful build.

#### Actual behavior

```
error FS0192 : internal error : primDestForallTy: not a forall type [C:\temp\vs2017-recharts\vs2017-recharts\vs2017-recharts.fsproj]

  Unhandled Exception: System.Exception: primDestForallTy: not a forall type
     at Microsoft.FSharp.Compiler.Tastops.primDestForallTy(TcGlobals g, TType ty)
     at Microsoft.FSharp.Compiler.Tastops.destForallTy(TcGlobals g, TType ty)
     at Microsoft.FSharp.Compiler.Tastops.applyForallTy(TcGlobals g, TType ty, FSharpList`1 tyargs)
     at Microsoft.FSharp.Compiler.Tastops.mkAppsAux(TcGlobals g, Expr f, TType fty, FSharpList`1 tyargsl, FSharpList`1 argsl, range m)
     at Microsoft.FSharp.Compiler.Tastops.MakeApplicationAndBetaReduceAux(TcGlobals g, Expr f, TType fty, FSharpList`1 tyargsl, FSharpList`1 argsl, range m)
     at Microsoft.FSharp.Compiler.IlxGen.GenGetStorageAndSequel(cenv cenv, CodeGenBuffer cgbuf, IlxGenEnv eenv, range m, TType typ, ILType ilTy, ValStorage storage, FSharpOption`1 storeSequel)
     at Microsoft.FSharp.Compiler.IlxGen.CodeGenMethodForExpr@1977.Invoke(CodeGenBuffer cgbuf, IlxGenEnv eenv)
     at Microsoft.FSharp.Compiler.IlxGen.CodeGenThen(cenv cenv, AssemblyBuilder mgbuf, FSharpList`1 entryPointInfo, String methodName, IlxGenEnv eenv, Int32 alreadyUsedArgs, Int32 alreadyUsedLocals, FSharpFun
  c`2 codeGenFunction, range m)
     at Microsoft.FSharp.Compiler.IlxGen.CodeGenMethod(cenv cenv, AssemblyBuilder mgbuf, FSharpList`1 entryPointInfo, String methodName, IlxGenEnv eenv, Int32 alreadyUsedArgs, Int32 alreadyUsedLocals, FSharpF
  unc`2 codeGenFunction, range m)
     at Microsoft.FSharp.Compiler.IlxGen.CodeGenMethodForExpr(cenv cenv, AssemblyBuilder mgbuf, EmitSequencePointState spReq, FSharpList`1 entryPointInfo, String methodName, IlxGenEnv eenv, Int32 alreadyUsedA
  rgs, Int32 alreadyUsedLocals, Expr expr0, sequel sequel0)
     at Microsoft.FSharp.Compiler.IlxGen.GenLambdaClosure(cenv cenv, CodeGenBuffer cgbuf, IlxGenEnv eenv, Boolean isLocalTypeFunc, FSharpOption`1 selfv, Expr expr)
     at Microsoft.FSharp.Compiler.IlxGen.GenLambda(cenv cenv, CodeGenBuffer cgbuf, IlxGenEnv eenv, Boolean isLocalTypeFunc, FSharpOption`1 selfv, Expr expr, sequel sequel)
     at Microsoft.FSharp.Compiler.IlxGen.GenBindingRhs(cenv cenv, CodeGenBuffer cgbuf, IlxGenEnv eenv, EmitSequencePointState sp, Val vspec, Expr e)
     at Microsoft.FSharp.Compiler.IlxGen.GenBindingAfterSequencePoint(cenv cenv, CodeGenBuffer cgbuf, IlxGenEnv eenv, EmitSequencePointState sp, Binding _arg8, FSharpOption`1 startScopeMarkOpt)
     at Microsoft.FSharp.Compiler.IlxGen.GenBindings@5402.Invoke(Binding bind)
     at Microsoft.FSharp.Primitives.Basics.List.iter[T](FSharpFunc`2 f, FSharpList`1 x)
     at Microsoft.FSharp.Collections.ListModule.Iterate[T](FSharpFunc`2 action, FSharpList`1 list)
     at Microsoft.FSharp.Compiler.IlxGen.GenModuleDef(cenv cenv, CodeGenBuffer cgbuf, QualifiedNameOfFile qname, List`1 lazyInitInfo, IlxGenEnv eenv, ModuleOrNamespaceExpr x)
     at Microsoft.FSharp.Compiler.IlxGen.GenModuleDefs@5834.Invoke(ModuleOrNamespaceExpr x)
     at Microsoft.FSharp.Primitives.Basics.List.iter[T](FSharpFunc`2 f, FSharpList`1 x)
     at Microsoft.FSharp.Collections.ListModule.Iterate[T](FSharpFunc`2 action, FSharpList`1 list)
     at Microsoft.FSharp.Compiler.IlxGen.GenModuleDef(cenv cenv, CodeGenBuffer cgbuf, QualifiedNameOfFile qname, List`1 lazyInitInfo, IlxGenEnv eenv, ModuleOrNamespaceExpr x)
     at Microsoft.FSharp.Compiler.IlxGen.GenModuleBinding(cenv cenv, CodeGenBuffer cgbuf, QualifiedNameOfFile qname, List`1 lazyInitInfo, IlxGenEnv eenv, range m, ModuleOrNamespaceBinding x)
     at Microsoft.FSharp.Compiler.IlxGen.GenModuleDef@5843-1.Invoke(ModuleOrNamespaceBinding x)
     at Microsoft.FSharp.Primitives.Basics.List.iter[T](FSharpFunc`2 f, FSharpList`1 x)
     at Microsoft.FSharp.Collections.ListModule.Iterate[T](FSharpFunc`2 action, FSharpList`1 list)
     at Microsoft.FSharp.Compiler.IlxGen.GenModuleDefs@5834.Invoke(ModuleOrNamespaceExpr x)
     at Microsoft.FSharp.Primitives.Basics.List.iter[T](FSharpFunc`2 f, FSharpList`1 x)
     at Microsoft.FSharp.Collections.ListModule.Iterate[T](FSharpFunc`2 action, FSharpList`1 list)
     at Microsoft.FSharp.Compiler.IlxGen.GenModuleDef(cenv cenv, CodeGenBuffer cgbuf, QualifiedNameOfFile qname, List`1 lazyInitInfo, IlxGenEnv eenv, ModuleOrNamespaceExpr x)
     at Microsoft.FSharp.Compiler.IlxGen.GenModuleDefs@5834.Invoke(ModuleOrNamespaceExpr x)
     at Microsoft.FSharp.Primitives.Basics.List.iter[T](FSharpFunc`2 f, FSharpList`1 x)
     at Microsoft.FSharp.Collections.ListModule.Iterate[T](FSharpFunc`2 action, FSharpList`1 list)
     at Microsoft.FSharp.Compiler.IlxGen.GenModuleDef(cenv cenv, CodeGenBuffer cgbuf, QualifiedNameOfFile qname, List`1 lazyInitInfo, IlxGenEnv eenv, ModuleOrNamespaceExpr x)
     at Microsoft.FSharp.Compiler.IlxGen.GenModuleExpr@5824.Invoke(Tuple`2 scopeMarks)
     at Microsoft.FSharp.Compiler.IlxGen.LocalScope[a](String nm, CodeGenBuffer cgbuf, FSharpFunc`2 f)
     at Microsoft.FSharp.Compiler.IlxGen.GenModuleExpr(cenv cenv, CodeGenBuffer cgbuf, QualifiedNameOfFile qname, List`1 lazyInitInfo, IlxGenEnv eenv, ModuleOrNamespaceExprWithSig x)
     at Microsoft.FSharp.Compiler.IlxGen.GenTopImpl@5943.Invoke(CodeGenBuffer cgbuf, IlxGenEnv eenv)
     at Microsoft.FSharp.Compiler.IlxGen.CodeGenThen(cenv cenv, AssemblyBuilder mgbuf, FSharpList`1 entryPointInfo, String methodName, IlxGenEnv eenv, Int32 alreadyUsedArgs, Int32 alreadyUsedLocals, FSharpFun
  c`2 codeGenFunction, range m)
     at Microsoft.FSharp.Compiler.IlxGen.CodeGenMethod(cenv cenv, AssemblyBuilder mgbuf, FSharpList`1 entryPointInfo, String methodName, IlxGenEnv eenv, Int32 alreadyUsedArgs, Int32 alreadyUsedLocals, FSharpF
  unc`2 codeGenFunction, range m)
     at Microsoft.FSharp.Compiler.IlxGen.GenTopImpl(cenv cenv, AssemblyBuilder mgbuf, FSharpOption`1 mainInfoOpt, IlxGenEnv eenv, TypedImplFile _arg11, FSharpFunc`2 optimizeDuringCodeGen)
     at Microsoft.FSharp.Compiler.IlxGen.eenv@6888-1.Invoke(IlxGenEnv eenv, Tuple`2 tupledArg)
     at Microsoft.FSharp.Collections.ListModule.Fold[T,TState](FSharpFunc`2 folder, TState state, FSharpList`1 list)
     at Microsoft.FSharp.Compiler.IlxGen.CodegenAssembly(cenv cenv, IlxGenEnv eenv, AssemblyBuilder mgbuf, FSharpList`1 fileImpls)
     at Microsoft.FSharp.Compiler.IlxGen.GenerateCode(cenv cenv, IlxGenEnv eenv, TypedAssemblyAfterOptimization _arg1, FSharpList`1 assemAttribs, FSharpList`1 moduleAttribs)
     at Microsoft.FSharp.Compiler.IlxGen.IlxAssemblyGenerator.GenerateCode(IlxGenOptions codeGenOpts, TypedAssemblyAfterOptimization typedAssembly, FSharpList`1 assemAttribs, FSharpList`1 moduleAttribs)
     at Microsoft.FSharp.Compiler.CompileOptions.GenerateIlxCode(IlxGenBackend ilxBackend, Boolean isInteractiveItExpr, Boolean isInteractiveOnMono, TcConfig tcConfig, TopAttribs topAttrs, TypedAssemblyAfterO
  ptimization optimizedImpls, String fragName, IlxAssemblyGenerator ilxGenerator)
     at Microsoft.FSharp.Compiler.Driver.main2b[a,b,c,d,e,f,g,h](FSharpOption`1 tcImportsCapture, FSharpOption`1 dynamicAssemblyCreator, Args`1 _arg1)
     at Microsoft.FSharp.Compiler.Driver.typecheckAndCompile(CompilationThreadToken ctok, String[] argv, Resolver legacyReferenceResolver, Boolean bannerAlreadyPrinted, Boolean openBinariesInMemory, Boolean d
  efaultCopyFSharpCore, Exiter exiter, ErrorLoggerProvider loggerProvider, FSharpOption`1 tcImportsCapture, FSharpOption`1 dynamicAssemblyCreator)
     at Microsoft.FSharp.Compiler.CommandLineMain.Driver.main(String[] argv)
     at Microsoft.FSharp.Compiler.CommandLineMain.main(String[] argv)
     at Microsoft.FSharp.Compiler.ErrorLogger.ErrorLoggerExtensions.ReraiseIfWatsonable(Exception exn)
     at Microsoft.FSharp.Compiler.ErrorLogger.ErrorLoggerExtensions.ErrorLogger.ErrorRecovery(ErrorLogger x, Exception exn, range m)
     at Microsoft.FSharp.Compiler.CommandLineMain.main(String[] argv)
Done Building Project "C:\temp\vs2017-recharts\vs2017-recharts\vs2017-recharts.fsproj" (default targets) -- FAILED.


Build FAILED.

"C:\temp\vs2017-recharts\vs2017-recharts\vs2017-recharts.fsproj" (default target) (1) ->
(CoreCompile target) ->
  error FS0192 : internal error : primDestForallTy: not a forall type [C:\temp\vs2017-recharts\vs2017-recharts\vs2017-recharts.fsproj]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:04.41
```

#### Related information 

This started to occur only when I upgraded to VS 15.6.4.

**Comment by dsyme** [comment]
@cartermp  This may be a regression though I'm not aware of its cause.

**Comment by dsyme** [comment]
@theprash I tried to repro this using the steps above with 15.6.5 and couldn't repro

```
1>------ Rebuild All started: Project: vs2017-recharts, Configuration: Debug Any CPU ------
1>vs2017-recharts -> C:\Users\dsyme\Downloads\vs2017-recharts\vs2017-recharts-master\vs2017-recharts\bin\Debug\netstandard2.0\vs2017-recharts.dll
========== Rebuild All: 1 succeeded, 0 failed, 0 skipped ==========
```

**Comment by dsyme** [comment]
Will close - please update the repro if you have it failing still, thanks
