### ISSUE TITLE
Crash VS 2015 RC with FSharp.Core

### ISSUE THREAD

**Issue by rfrerebe** [Microsoft/visualfsharp#472]
Hi,

I got a null Ref exception with Visual Studio 2015 RC when opening a FSharp solution
.NET framework 4.6
FSharp version is 4.40.22810.0
Also I couldn't get FSharp.Core.pdb from Microsoft Symbols Servers
I have a dump if needed.

Here is the stack trace :
```
   at Microsoft.FSharp.Core.LanguagePrimitives.IntrinsicFunctions.UnboxGeneric[T](Object source)
   at FSharpVSPowerTools.StandardCommandDispatcher.Register(IVsTextView interopTextView, IWpfTextView textView, CodeFormattingServices services)
   at FSharpVSPowerTools.CodeFormattingHookHelper.RegisterCommandDispatcher(IWpfTextView wpfTextView)
   at FSharpVSPowerTools.CodeFormattingHookHelper.<>c__DisplayClass1.<TextViewCreated>b__0()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
```

**Comment by enricosada** [comment]
stacktrace:
`at FSharpVSPowerTools.CodeFormattingHookHelper.<>c__DisplayClass1.<TextViewCreated>b__0()`

it think is a https://github.com/fsprojects/VisualFSharpPowerTools issue

**Comment by latkin** [comment]
Yes, this appears to be a Power Tools issue, please open at that repo.

**Comment by rfrerebe** [comment]
Thanks, I try without it,a d report them.
