### ISSUE TITLE
Inspecting Microsoft.FSharp.Compiler.Tast.Entity in debugger crashes the debugger

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#5021]
Rider does not crash, but some properties are timed out to obtain: 

![image](https://user-images.githubusercontent.com/873919/40607518-6b7b7f22-6271-11e8-9835-aa5121ca0a38.png)

**Comment by vasily-kirichenko** [comment]
```
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------




   at Microsoft.FSharp.Compiler.Tast.Entity.get_FSharpObjectModelTypeInfo()

   at <StartupCode$FSharp-Compiler-Private>.$Service.isStructTyconRef@1317.Invoke(EntityRef tyconRef)

   at <StartupCode$FSharp-Compiler-Private>.$Service.GetSemanticClassification@1322-1.Invoke(CapturedNameResolution cnr)

   at Microsoft.FSharp.Collections.Internal.IEnumerator.choose@165.System-Collections-IEnumerator-MoveNext()

   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)

   at Microsoft.FSharp.Collections.SeqModule.ToArray[T](IEnumerable`1 source)

   at <StartupCode$FSharp-Compiler-Private>.$Service.GetSemanticClassification@1272.Invoke(Unit unitVar0)

   at Microsoft.FSharp.Compiler.SourceCodeServices.ErrorScope.Protect[a](range m, FSharpFunc`2 f, FSharpFunc`2 err)

   at Microsoft.FSharp.Compiler.SourceCodeServices.TypeCheckInfo.GetSemanticClassification(FSharpOption`1 range)

   at <StartupCode$FSharp-Compiler-Private>.$Service.GetSemanticClassification@2070-9.Invoke(TypeCheckInfo scope)

   at <StartupCode$FSharp-Editor>.$ClassificationService.Microsoft-CodeAnalysis-Editor-IEditorClassificationService-AddSemanticClassificationsAsync@52-4.Invoke(Tuple`3 _arg11)

   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvokeNoHijackCheck[a,b](AsyncActivation`1 ctxt, FSharpFunc`2 userCode, b result1)

   at Microsoft.VisualStudio.FSharp.Editor.Pervasive.Async.map@186-2.Invoke(AsyncActivation`1 ctxt)

   at Microsoft.VisualStudio.FSharp.Editor.FSharpCheckerExtensions.parseAndCheckFile@30-2.Invoke(AsyncActivation`1 ctxt)

   at <StartupCode$FSharp-Compiler-Private>.$Service.ParseAndCheckFileInProject@2718-11.Invoke(AsyncActivation`1 ctxt)

   at <StartupCode$FSharp-Compiler-Private>.$Service.loop@2590-120.Invoke(AsyncActivation`1 ctxt)

   at Microsoft.FSharp.Compiler.SourceCodeServices.Parser.CheckOneFile@1761-36.Invoke(AsyncActivation`1 ctxt)

   at Microsoft.FSharp.Compiler.SourceCodeServices.Parser.CheckOneFile@1734-28.Invoke(AsyncActivation`1 ctxt)

   at Microsoft.FSharp.Compiler.AbstractIL.Internal.Library.EventuallyModule.loop@840-24.Invoke(AsyncActivation`1 ctxt)

   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction)

   at Microsoft.FSharp.Control.TrampolineHolder.ExecuteWithTrampoline(FSharpFunc`2 firstAction)

   at <StartupCode$FSharp-Core>.$Async.-ctor@166-1.Invoke(Object o)

   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()

   at System.Threading.ThreadPoolWorkQueue.Dispatch()

   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()


---------------------------
Abort   Retry   Ignore   
---------------------------
```

**Comment by vasily-kirichenko** [comment]
```
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------




   at Microsoft.FSharp.Compiler.Tast.Entity.get_ILTyconInfo()

   at <StartupCode$FSharp-Compiler-Private>.$Service.isStructTyconRef@1317.Invoke(EntityRef tyconRef)

   at <StartupCode$FSharp-Compiler-Private>.$Service.GetSemanticClassification@1322-1.Invoke(CapturedNameResolution cnr)

   at Microsoft.FSharp.Collections.Internal.IEnumerator.choose@165.System-Collections-IEnumerator-MoveNext()

   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)

   at Microsoft.FSharp.Collections.SeqModule.ToArray[T](IEnumerable`1 source)

   at <StartupCode$FSharp-Compiler-Private>.$Service.GetSemanticClassification@1272.Invoke(Unit unitVar0)

   at Microsoft.FSharp.Compiler.SourceCodeServices.ErrorScope.Protect[a](range m, FSharpFunc`2 f, FSharpFunc`2 err)

   at Microsoft.FSharp.Compiler.SourceCodeServices.TypeCheckInfo.GetSemanticClassification(FSharpOption`1 range)

   at <StartupCode$FSharp-Compiler-Private>.$Service.GetSemanticClassification@2070-9.Invoke(TypeCheckInfo scope)

   at <StartupCode$FSharp-Editor>.$ClassificationService.Microsoft-CodeAnalysis-Editor-IEditorClassificationService-AddSemanticClassificationsAsync@52-4.Invoke(Tuple`3 _arg11)

   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvokeNoHijackCheck[a,b](AsyncActivation`1 ctxt, FSharpFunc`2 userCode, b result1)

   at Microsoft.VisualStudio.FSharp.Editor.Pervasive.Async.map@186-2.Invoke(AsyncActivation`1 ctxt)

   at Microsoft.VisualStudio.FSharp.Editor.FSharpCheckerExtensions.parseAndCheckFile@30-2.Invoke(AsyncActivation`1 ctxt)

   at <StartupCode$FSharp-Compiler-Private>.$Service.ParseAndCheckFileInProject@2718-11.Invoke(AsyncActivation`1 ctxt)

   at <StartupCode$FSharp-Compiler-Private>.$Service.loop@2590-120.Invoke(AsyncActivation`1 ctxt)

   at Microsoft.FSharp.Compiler.SourceCodeServices.Parser.CheckOneFile@1761-36.Invoke(AsyncActivation`1 ctxt)

   at Microsoft.FSharp.Compiler.SourceCodeServices.Parser.CheckOneFile@1734-28.Invoke(AsyncActivation`1 ctxt)

   at Microsoft.FSharp.Compiler.AbstractIL.Internal.Library.EventuallyModule.loop@840-24.Invoke(AsyncActivation`1 ctxt)

   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction)

   at Microsoft.FSharp.Control.TrampolineHolder.ExecuteWithTrampoline(FSharpFunc`2 firstAction)

   at <StartupCode$FSharp-Core>.$Async.-ctor@166-1.Invoke(Object o)

   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()

   at System.Threading.ThreadPoolWorkQueue.Dispatch()

   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()


---------------------------
Abort   Retry   Ignore   
---------------------------
```

**Comment by vasily-kirichenko** [comment]
```
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------




   at Microsoft.FSharp.Compiler.Tast.Entity.get_ILTyconInfo()

   at Microsoft.FSharp.Compiler.Tast.Entity.get_ILTyconRawMetadata()

   at <StartupCode$FSharp-Compiler-Private>.$Service.isStructTyconRef@1317.Invoke(EntityRef tyconRef)

   at <StartupCode$FSharp-Compiler-Private>.$Service.GetSemanticClassification@1322-1.Invoke(CapturedNameResolution cnr)

   at Microsoft.FSharp.Collections.Internal.IEnumerator.choose@165.System-Collections-IEnumerator-MoveNext()

   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)

   at Microsoft.FSharp.Collections.SeqModule.ToArray[T](IEnumerable`1 source)

   at <StartupCode$FSharp-Compiler-Private>.$Service.GetSemanticClassification@1272.Invoke(Unit unitVar0)

   at Microsoft.FSharp.Compiler.SourceCodeServices.ErrorScope.Protect[a](range m, FSharpFunc`2 f, FSharpFunc`2 err)

   at Microsoft.FSharp.Compiler.SourceCodeServices.TypeCheckInfo.GetSemanticClassification(FSharpOption`1 range)

   at <StartupCode$FSharp-Compiler-Private>.$Service.GetSemanticClassification@2070-9.Invoke(TypeCheckInfo scope)

   at <StartupCode$FSharp-Editor>.$ClassificationService.Microsoft-CodeAnalysis-Editor-IEditorClassificationService-AddSemanticClassificationsAsync@52-4.Invoke(Tuple`3 _arg11)

   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvokeNoHijackCheck[a,b](AsyncActivation`1 ctxt, FSharpFunc`2 userCode, b result1)

   at Microsoft.VisualStudio.FSharp.Editor.Pervasive.Async.map@186-2.Invoke(AsyncActivation`1 ctxt)

   at Microsoft.VisualStudio.FSharp.Editor.FSharpCheckerExtensions.parseAndCheckFile@30-2.Invoke(AsyncActivation`1 ctxt)

   at <StartupCode$FSharp-Compiler-Private>.$Service.ParseAndCheckFileInProject@2718-11.Invoke(AsyncActivation`1 ctxt)

   at <StartupCode$FSharp-Compiler-Private>.$Service.loop@2590-120.Invoke(AsyncActivation`1 ctxt)

   at Microsoft.FSharp.Compiler.SourceCodeServices.Parser.CheckOneFile@1761-36.Invoke(AsyncActivation`1 ctxt)

   at Microsoft.FSharp.Compiler.SourceCodeServices.Parser.CheckOneFile@1734-28.Invoke(AsyncActivation`1 ctxt)

   at Microsoft.FSharp.Compiler.AbstractIL.Internal.Library.EventuallyModule.loop@840-24.Invoke(AsyncActivation`1 ctxt)

   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction)

   at Microsoft.FSharp.Control.TrampolineHolder.ExecuteWithTrampoline(FSharpFunc`2 firstAction)

   at <StartupCode$FSharp-Core>.$Async.-ctor@166-1.Invoke(Object o)

   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()

   at System.Threading.ThreadPoolWorkQueue.Dispatch()

   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()


---------------------------
Abort   Retry   Ignore   
---------------------------
```

**Comment by abelbraaksma** [comment]
This is interesting, I have had the same with some large record types that crash the debugger (in my case when you scroll down through the fields in the inspection window or locals window), but I never succeeded on making a small repro. So I can confirm this happens with other scenarios as well

**Comment by cartermp** [comment]
Not sure if this is on our end or the debugger. @dsyme any thoughts?

**Comment by vasily-kirichenko** [comment]
@cartermp those _properties_ raise assert exceptions, I suggest to make them methods in order to prevent debuggers to auto evaluate them.

**Comment by abelbraaksma** [comment]
The more general question to ask is whether the property evaluator is allowed to crash at all. And debug assertions are devils, but should be captured just like other exceptions. Though I'm not sure that possible, perhaps the debugger of VS already handles a a assertions specially in a  first chance handler, overriding other handlers?

**Comment by dsyme** [comment]
I don't think it's feasible to stop the properties raising exceptions, especially in the presence of incomplete reference sets

The assert exceptions are painful however and we should likely just remove the asserts in these cases

**Comment by dsyme** [comment]
I'll go through and fix things up

**Comment by dsyme** [comment]
See https://github.com/Microsoft/visualfsharp/issues/5021

**Comment by abelbraaksma** [comment]
> I don't think it's feasible to stop the properties raising exceptions in general,

@dsyme, currently it shows in the inspection window a text "evaluating threw an exception", it doesn't propagate the exception to the VS editor or the debugger (since you are usually on pause-all-threads, that would be odd, wouldn't it?)
