### ISSUE TITLE
Exception pops up while editing F# code in Visual Studio 2017, log shows TaskCanceledException

### ISSUE THREAD

**Issue by abelbraaksma** [Microsoft/visualfsharp#5033]
I just received the following exception while editing in Visual Studio 2017, 15.7.2 RTM.

![image](https://user-images.githubusercontent.com/16015770/40690303-b50dd87a-63a6-11e8-96f9-59b55199c733.png)

### Repro steps

No repro, sorry, but it has happened in the past, in which case I always just clicked it away. It seems to be in the same line as other reports (including mine) about deteriorating editing experience where the editor quickly gets slower and slower while using it.

### Expected behavior

No exceptions should popup.

### Actual behavior

Exception. This is what the ActivityLog shows:

```text
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Roslyn.Utilities.TaskExtensions.WaitAndGetResult_CanCallOnBackground[T](Task`1 task, CancellationToken cancellationToken)
   at Roslyn.Utilities.TaskExtensions.WaitAndGetResult[T](Task`1 task, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.ModelComputation`1.WaitForController()
   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.Session`3.WaitForController()
   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.AbstractController`4.WaitForController()
   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.SignatureHelp.Controller.ChangeSelection(Action computationAction)
   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.SignatureHelp.Controller.TryHandleUpKey()
   at Microsoft.CodeAnalysis.Editor.CommandHandlers.SignatureHelpCommandHandler.TryHandleUpKey(UpKeyCommandArgs commandArgs)
   at Microsoft.CodeAnalysis.Editor.CommandHandlers.AbstractIntelliSenseCommandHandler.ExecuteCommand(UpKeyCommandArgs args, Action nextHandler, CommandExecutionContext context)
   at Microsoft.VisualStudio.Commanding.CommandHandlerExtensions.ExecuteCommand[T](ICommandHandler commandHandler, T args, Action nextCommandHandler, CommandExecutionContext executionContext)
   at Microsoft.VisualStudio.UI.Text.Commanding.Implementation.EditorCommandHandlerService.<>c__DisplayClass14_1`1.<Execute>b__1()
   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.CallExtensionPoint(Object errorSource, Action call)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by abelbraaksma** [comment]
PS: if this happens again, is there a more substantial log that I can switch on and/or send that could help us further (apart from profiling and recording)?

**Comment by cartermp** [comment]
Not that I'm aware of, unfortunately. The stack trace there is basically saying, "some concurrent work was cancelled", which leads me to believe that a _different_ exception was thrown somewhere else. But without a reliable reproduction, it's impossible to say what part of the tools ends up throwing that exception.

**Comment by cartermp** [comment]
Given that this is a task being cancelled in Roslyn, my guess is that there was some other error or timeout associated with the action you took. I don't think there is a specific bug that is unrelated to just the general pile of performance issues you have with the F# compiler, Visual Studio, and your codebase 😢 

I'll close this out. If you see it repeatedly for something that doesn't appear to be perf-related, please do ping and we can re-open it.
