### ISSUE TITLE
Unexpected exception raised in compiler: The lists had different lengths.

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#5200]
I'm afraid it's caused by the recent removing `List.take` from `illib.fs` and (automatically) use of the FSharp.Core's `List.take` instead of `List.truncate` (illibs' `take` works as `truncate`, not as FSharp.Core's `take`).

---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------
Unexpected exception raised in compiler: The lists had different lengths.
list2 is 1 element shorter than list1

Parameter name: list2 (ArgumentException)
Microsoft.FSharp.Compiler.ErrorLogger+InternalError: The lists had different lengths.
list2 is 1 element shorter than list1

Parameter name: list2 (ArgumentException)C:\Users\kirichenko\source\repos\ConsoleApplication6\ConsoleApplication6\Program.fs (2,0--30,0) IsSynthetic=false

   at Microsoft.FSharp.Compiler.ErrorLogger.ErrorLoggerExtensions.ErrorLogger.ErrorR(ErrorLogger x, Exception exn)

   at Microsoft.FSharp.Compiler.ErrorLogger.ErrorLoggerExtensions.ErrorLogger.ErrorRecovery(ErrorLogger x, Exception exn, range m)

   at Microsoft.FSharp.Compiler.TypeChecker.TcModuleOrNamespaceElementNonMutRec@16739-18.Invoke(Exception _arg3)

   at Microsoft.FSharp.Compiler.AbstractIL.Internal.Library.EventuallyModule.bind@856-1.Invoke(CompilationThreadToken ctok)

   at Microsoft.FSharp.Compiler.AbstractIL.Internal.Library.EventuallyModule.bind@856-1.Invoke(CompilationThreadToken ctok)

   at Microsoft.FSharp.Compiler.AbstractIL.Internal.Library.EventuallyModule.bind@856-1.Invoke(CompilationThreadToken ctok)

   at Microsoft.FSharp.Compiler.AbstractIL.Internal.Library.EventuallyModule.catch@865-1.Invoke(CompilationThreadToken ctok)

   at Microsoft.FSharp.Compiler.AbstractIL.Internal.Library.EventuallyModule.bind@856-1.Invoke(CompilationThreadToken ctok)

   at Microsoft.FSharp.Compiler.AbstractIL.Internal.Library.EventuallyModule.bind@856-1.Invoke(CompilationThreadToken ctok)

   at Microsoft.FSharp.Compiler.AbstractIL.Internal.Library.EventuallyModule.bind@856-1.Invoke(CompilationThreadToken ctok)

   at Microsoft.FSharp.Compiler.AbstractIL.Internal.Library.EventuallyModule.bind@856-1.Invoke(CompilationThreadToken ctok)

   at Microsoft.FSharp.Compiler.AbstractIL.Internal.Library.EventuallyModule.bind@856-1.Invoke(CompilationThreadToken ctok)

   at Microsoft.FSharp.Compiler.AbstractIL.Internal.Library.EventuallyModule.catch@865-1.Invoke(CompilationThreadToken ctok)

   at Microsoft.FSharp.Compiler.AbstractIL.Internal.Library.EventuallyModule.bind@856-1.Invoke(CompilationThreadToken ctok)

   at Microsoft.FSharp.Compiler.AbstractIL.Internal.Library.EventuallyModule.bind@856-1.Invoke(CompilationThreadToken ctok)

   at Microsoft.FSharp.Compiler.AbstractIL.Internal.Library.EventuallyModule.loop@829-20.Invoke(CompilationThreadToken ctok, Eventually`1 ev2)

   at Microsoft.FSharp.Compiler.SourceCodeServices.Parser.CheckOneFile@1727-24.Invoke(CompilationThreadToken ctok)

   at <StartupCode$FSharp-Compiler-Private>.$Reactor.EnqueueAndAwaitOpAsync@174-2.Invoke(CompilationThreadToken ctok)

   at <StartupCode$FSharp-Compiler-Private>.$Reactor.loop@70-99.Invoke(FSharpOption`1 _arg2)

   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvokeNoHijackCheck[a,b](AsyncActivation`1 ctxt, FSharpFunc`2 userCode, b result1)

   at <StartupCode$FSharp-Compiler-Private>.$Reactor.loop@57-97.Invoke(AsyncActivation`1 ctxt)

   at <StartupCode$FSharp-Core>.$Mailbox.processFirstArrival@344-11.Invoke(AsyncActivation`1 ctxt)

   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction)

   at <StartupCode$FSharp-Core>.$Async.-ctor@167-1.Invoke(Object o)

   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()

   at System.Threading.ThreadPoolWorkQueue.Dispatch()

   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

---------------------------
Abort   Retry   Ignore   
---------------------------

**Comment by cartermp** [comment]
@KevinRansom / @TIHan FYI

**Comment by cartermp** [comment]
Closing in favor of #5468 where the issue has a repro
