### ISSUE TITLE
Critical capabilities changes were detected without any change made to the project

### ISSUE THREAD

**Issue by vsfeedback** [Microsoft/visualfsharp#5205]
1. git clone https://github.com/dotnet/docfx.git
2. open the All.sln
3. error: The project system has encountered an error.

Internal error: Critical capabilities changes were detected without any change made to the project 'Microsoft.DocAsCode.Metadata.ManagedReference.FSharp.Tests.fsproj', and forces the project to be reloaded.  Potential capabilities involved: 'FSharp'.

I meet this error after upgrading to vs 15.7.3. I found several issues with similar error message that have been fixed in 15.3, but I think it's not the same issue for me.

```
Details:

LimitedFunctionality
System.AggregateException: One or more errors occurred. ---&gt; System.InvalidOperationException: Internal error: Critical capabilities changes were detected without any change made to the project 'Microsoft.DocAsCode.Metadata.ManagedReference.FSharp.fsproj', and forces the project to be reloaded.  Potential capabilities involved: 'FSharp'.
   at Microsoft.VisualStudio.ProjectSystem.ProjectCapabilitiesRequirementsService.&lt;RequestReloadForIncompatibleCapabilitiesAsync&gt;d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.ProjectSystem.CommonProjectSystemTools.Rethrow(Exception ex)
   at Microsoft.VisualStudio.ProjectSystem.ProjectErrorReporting.&lt;&gt;c__DisplayClass6_0.&lt;SubmitErrorReport&gt;b__0()
   at Microsoft.VisualStudio.ProjectSystem.ExceptionFilter.&lt;&gt;c__DisplayClass2_0.&lt;Guard&gt;b__0()
   at GuardMethodClass.GuardMethod(Func`1 , Func`2 , Func`2 )
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
   --- End of inner exception stack trace ---
---&gt; (Inner Exception #0) System.InvalidOperationException: Internal error: Critical capabilities changes were detected without any change made to the project 'Microsoft.DocAsCode.Metadata.ManagedReference.FSharp.fsproj', and forces the project to be reloaded.  Potential capabilities involved: 'FSharp'.
   at Microsoft.VisualStudio.ProjectSystem.ProjectCapabilitiesRequirementsService.&lt;RequestReloadForIncompatibleCapabilitiesAsync&gt;d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.ProjectSystem.CommonProjectSystemTools.Rethrow(Exception ex)
   at Microsoft.VisualStudio.ProjectSystem.ProjectErrorReporting.&lt;&gt;c__DisplayClass6_0.&lt;SubmitErrorReport&gt;b__0()
   at Microsoft.VisualStudio.ProjectSystem.ExceptionFilter.&lt;&gt;c__DisplayClass2_0.&lt;Guard&gt;b__0()
   at GuardMethodClass.GuardMethod(Func`1 , Func`2 , Func`2 )
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)&lt;---
```
_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/267201/critical-capabilities-changes-were-detected-withou-1.html
VSTS ticketId: 626735_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by cartermp** [comment]
This might need to go under dotnet/project-system

**Comment by cartermp** [comment]
@TIHan FYI

**Comment by davkean** [comment]
This issue was moved to dotnet/project-system#3673

**Comment by cartermp** [comment]
Thanks @davkean
