### ISSUE TITLE
Assertion: This must be called from the GUI thread

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#5296]
VS 15.7
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------
This must be called from the GUI thread

   at Microsoft.VisualStudio.FSharp.ProjectSystem.UIThread.MustBeCalledFromUIThread()

   at Microsoft.VisualStudio.FSharp.ProjectSystem.ProjectNode.SetupProjectGlobalPropertiesThatAllProjectSystemsMustSet()

   at Microsoft.VisualStudio.FSharp.ProjectSystem.ProjectNode.SetBuildProject(Project newBuildProject)

   at Microsoft.VisualStudio.FSharp.ProjectSystem.FSharpProjectNode.SetBuildProject(Project newProj)

   at Microsoft.VisualStudio.FSharp.ProjectSystem.ProjectNode.set_BuildProject(Project value)

   at Microsoft.VisualStudio.FSharp.ProjectSystem.ProjectFactory.PreCreateForOuter(IntPtr outerProjectIUnknown)

   at Microsoft.VisualStudio.Shell.Flavor.FlavoredProjectFactoryBase.Microsoft.VisualStudio.Shell.Flavor.IVsAggregatableProjectFactoryCorrected.PreCreateForOuter(IntPtr outerProjectIUnknown, IntPtr& projectIUnknown)

   at Microsoft.VisualStudio.Shell.Interop.IVsCreateAggregateProject.CreateAggregateProject(String pszProjectTypeGuids, String pszFilename......

<truncated>
---------------------------
Abort   Retry   Ignore   
---------------------------

**Comment by vasily-kirichenko** [comment]
And

---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------
This must be called from the GUI thread



   at Microsoft.VisualStudio.FSharp.ProjectSystem.UIThread.MustBeCalledFromUIThread()

   at Microsoft.VisualStudio.FSharp.ProjectSystem.ProjectNode.InvokeMsBuild(String target, IEnumerable`1 extraProperties)

   at Microsoft.VisualStudio.FSharp.ProjectSystem.FSharpProjectNode.InvokeMsBuild(String target, IEnumerable`1 extraProperties)

   at Microsoft.VisualStudio.FSharp.ProjectSystem.FSharpProjectNode.ComputeSourcesAndFlags()

   at Microsoft.VisualStudio.FSharp.ProjectSystem.FSharpProjectNode.Microsoft-VisualStudio-FSharp-Editor-IProvideProjectSite-GetProjectSite()

   at Microsoft.VisualStudio.FSharp.Editor.IProvideProjectSite.GetProjectSite()

   at Microsoft.VisualStudio.FSharp.Editor.FSharpLanguageService.SetupProjectFile(IProvideProjectSite siteProvider, VisualStudioWorkspaceImpl workspace, String userOpName)

   at <StartupCode$FSharp-Editor>.$LanguageService.setupProjectsAfterSolutionOpen@486-12.Invoke(Unit _arg17)

   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvokeNoHijackCheck[a,b](AsyncActivation`1 ctxt, FSharpFunc`2 userCode, b result1)

   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction)

   at <StartupCode$FSharp-Core>.$Async.-ctor@161.Invoke(Object o)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

   at System.Windows.Threading.DispatcherOperation.InvokeImpl()

   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)

   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)

   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)

   at System.Windows.Threading.DispatcherOperation.Invoke()

   at System.Windows.Threading.Dispatcher.ProcessQueue()

   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)

   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)


---------------------------
Abort   Retry   Ignore   
---------------------------

**Comment by vasily-kirichenko** [comment]
This thing makes running debug version is impossible.

**Comment by vasily-kirichenko** [comment]
:) There is still no combination of a branch + VS version that can be built and tested.

**Comment by rojepp** [comment]
I F5-ed today and didn't see this FWIW

**Comment by cartermp** [comment]
I believe this has been fixed in 15.8, where a routine that initializes some info on the UI thread was handled properly. I aimed to close this when it released, but due to #5571 and #5572 I got distracted. Closing!
