### ISSUE TITLE
Assertion: The SynchronizationContext must be captured before calling this method

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#5303]
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------
The SynchronizationContext must be captured before calling this method

   at Microsoft.VisualStudio.FSharp.ProjectSystem.UIThread.Run(Action action)

   at Microsoft.VisualStudio.FSharp.ProjectSystem.IDEBuildLogger.AddToErrorList(BuildEventArgs errorEvent, String subcategory, String errorCode, String file, Int32 startLine, Int32 startColumn, Int32 endLine, Int32 endColumn)

   at Microsoft.VisualStudio.FSharp.ProjectSystem.IDEBuildLogger.ErrorHandler(Object sender, BuildErrorEventArgs errorEvent)

   at Microsoft.Build.Framework.BuildErrorEventHandler.Invoke(Object sender, BuildErrorEventArgs e)

   at Microsoft.Build.Utilities.MuxLogger.SubmissionRecord.RaiseErrorEvent(Object sender, BuildErrorEventArgs buildEvent)

   at Microsoft.Build.BackEnd.Logging.EventSourceSink.RaiseErrorEvent(Object sender, BuildErrorEventArgs buildEvent)

   at Microsoft.Build.BackEnd.Logging.EventSourceSink.Consume(BuildEventArgs buildEvent)

   at Microsoft.Build.BackEnd.Logging.EventSourceSink.Consume(BuildEventArgs buildEvent, Int32 sinkId)

   at Microsoft.Build.BackEnd.Logging.EventRedirectorToSink.Microsoft.Build.Framework.IEventRedirector.ForwardEvent(BuildEventArgs buildEvent)

   at Microsoft.Build.BackEnd.Logging.CentralForwardingLogger.EventSource_AnyEventRaised(Object sender, BuildEventArgs buildEvent)

   at Microsoft.Build.BackEnd.Logging.EventSourceSink.RaiseAnyEvent(Object sender, BuildEventArgs buildEvent)

   at Microsoft.Build.BackEnd.Logging.EventSourceSink.RaiseErrorEvent(Object sender, BuildErrorEventArgs buildEvent)

   at Microsoft.Build.BackEnd.Logging.EventSourceSink.Consume(BuildEventArgs buildEvent)

   at Microsoft.Build.BackEnd.Logging.LoggingService.RouteBuildEvent(BuildEventArgs eventArg)

   at Microsoft.Build.BackEnd.Logging.LoggingService.RouteBuildEvent(Object loggingEvent)

   at Microsoft.Build.BackEnd.Logging.LoggingService.LoggingEventProcessor(Object loggingEvent)

   at Microsoft.Build.BackEnd.Logging.LoggingService.<CreateLoggingEventQueue>b__98_0(Object loggingEvent)

   at System.Threading.Tasks.Dataflow.ActionBlock`1.ProcessMessage(Action`1 action, KeyValuePair`2 messageWithId)

   at System.Threading.Tasks.Dataflow.ActionBlock`1.<>c__DisplayClass5.<.ctor>b__0(KeyValuePair`2 messageWithId)

   at System.Threading.Tasks.Dataflow.Internal.TargetCore`1.ProcessMessagesLoopCore()

   at System.Threading.Tasks.Dataflow.Internal.TargetCore`1.<ProcessAsyncIfNecessary_Slow>b__3(Object thisTargetCore)

   at System.Threading.Tasks.Task.InnerInvoke()

   at System.Threading.Tasks.Task.Execute()

   at System.Threading.Tasks.Task.ExecutionContextCallback(Object obj)

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)

   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)

   at System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()

   at System.Threading.ThreadPoolWorkQueue.Dispatch()

   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

---------------------------
Abort   Retry   Ignore   
---------------------------

**Comment by cartermp** [comment]
Fixed by #5364
