### ISSUE TITLE
CodeLens/LineLens fails to load for open file upon package restore or open file at startup

### ISSUE THREAD

**Issue by chadunit** [Microsoft/visualfsharp#5959]
#### Issue 1:

The very first time loading a clean solution, when opening a .fs file before the package manager has restored packages, no CodeLens annotations ever appear even after package manager finishes and QuickInfo popups become enabled. The F# Language Service outputs repeating messages indefinitely despite no user activity occurring:

```
[F#][INFO 07:12:37 PM] Rechecking code due to buffer edit!
[F#][INFO 07:12:39 PM] Rechecking code due to buffer edit!
[F#][INFO 07:12:41 PM] Rechecking code due to buffer edit!
[F#][INFO 07:12:43 PM] Rechecking code due to buffer edit!
[F#][INFO 07:12:45 PM] Rechecking code due to buffer edit!
[F#][INFO 07:12:47 PM] Rechecking code due to buffer edit!
[F#][INFO 07:12:48 PM] Rechecking code due to buffer edit!
[F#][INFO 07:12:50 PM] Rechecking code due to buffer edit!
[F#][INFO 07:12:52 PM] Rechecking code due to buffer edit!
[F#][INFO 07:12:54 PM] Rechecking code due to buffer edit!
[F#][INFO 07:12:56 PM] Rechecking code due to buffer edit!
[F#][INFO 07:12:58 PM] Rechecking code due to buffer edit!
[F#][INFO 07:12:59 PM] Rechecking code due to buffer edit!
[F#][INFO 07:13:01 PM] Rechecking code due to buffer edit!
[F#][INFO 07:13:03 PM] Rechecking code due to buffer edit!
[F#][INFO 07:13:05 PM] Rechecking code due to buffer edit!
[F#][INFO 07:13:07 PM] Rechecking code due to buffer edit!
[F#][INFO 07:13:08 PM] Rechecking code due to buffer edit!
[F#][INFO 07:13:10 PM] Rechecking code due to buffer edit!
[F#][INFO 07:13:10 PM] Rechecking code due to buffer edit!
[F#][INFO 07:13:12 PM] Rechecking code due to buffer edit!
[F#][INFO 07:13:12 PM] Rechecking code due to buffer edit!
[F#][INFO 07:13:14 PM] Rechecking code due to buffer edit!
[F#][INFO 07:13:15 PM] Rechecking code due to buffer edit!
[F#][INFO 07:13:16 PM] Rechecking code due to buffer edit!
[F#][INFO 07:13:18 PM] Rechecking code due to buffer edit!
[F#][INFO 07:13:19 PM] Rechecking code due to buffer edit!
[F#][INFO 07:13:21 PM] Rechecking code due to buffer edit!
[F#][INFO 07:13:23 PM] Rechecking code due to buffer edit!
[F#][INFO 07:13:25 PM] Rechecking code due to buffer edit!
[F#][INFO 07:13:27 PM] Rechecking code due to buffer edit!
[F#][INFO 07:13:28 PM] Rechecking code due to buffer edit!
```

#### Issue 2:

With VS configured to `Reopen documents on solution load` in Projects and Solutions > General, then closing VS with an open .fs file and restarting, no CodeLens annotations appear, with F# Language Service outputting:

```
[F#][INFO 07:18:23 PM] Rechecking code due to buffer edit!
[F#][ERROR 07:18:23 PM] Line Lens startup failed with: System.ArgumentException: The option value was None
Parameter name: option
   at Microsoft.FSharp.Core.OptionModule.GetValue[T](FSharpOption`1 option)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at <StartupCode$FSharp-Editor>.$FSharpCodeLensService.clo@143-174.Invoke(Unit _arg12)
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvokeNoHijackCheck[a,b](AsyncActivation`1 ctxt, FSharpFunc`2 userCode, b result1)
   at <StartupCode$FSharp-Editor>.$FSharpCodeLensService.clo@142-172.Invoke(AsyncActivation`1 ctxt)
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction)
[F#][INFO 07:18:24 PM] Rechecking code due to buffer edit!
[F#][ERROR 07:18:24 PM] Line Lens startup failed with: System.ArgumentException: The option value was None
Parameter name: option
   at Microsoft.FSharp.Core.OptionModule.GetValue[T](FSharpOption`1 option)
   at System.Lazy`1.CreateValue()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Lazy`1.get_Value()
   at <StartupCode$FSharp-Editor>.$FSharpCodeLensService.clo@143-174.Invoke(Unit _arg12)
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvokeNoHijackCheck[a,b](AsyncActivation`1 ctxt, FSharpFunc`2 userCode, b result1)
   at <StartupCode$FSharp-Editor>.$FSharpCodeLensService.clo@142-172.Invoke(AsyncActivation`1 ctxt)
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction)
[F#][INFO 07:18:25 PM] Rechecking code due to buffer edit!
[F#][ERROR 07:18:25 PM] Line Lens startup failed with: System.ArgumentException: The option value was None
Parameter name: option
   at Microsoft.FSharp.Core.OptionModule.GetValue[T](FSharpOption`1 option)
   at System.Lazy`1.CreateValue()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Lazy`1.get_Value()
   at <StartupCode$FSharp-Editor>.$FSharpCodeLensService.clo@143-174.Invoke(Unit _arg12)
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvokeNoHijackCheck[a,b](AsyncActivation`1 ctxt, FSharpFunc`2 userCode, b result1)
   at <StartupCode$FSharp-Editor>.$FSharpCodeLensService.clo@142-172.Invoke(AsyncActivation`1 ctxt)
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction)
[F#][INFO 07:18:26 PM] Rechecking code due to buffer edit!
[F#][ERROR 07:18:26 PM] Line Lens startup failed with: System.ArgumentException: The option value was None
Parameter name: option
   at Microsoft.FSharp.Core.OptionModule.GetValue[T](FSharpOption`1 option)
   at System.Lazy`1.CreateValue()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Lazy`1.get_Value()
   at <StartupCode$FSharp-Editor>.$FSharpCodeLensService.clo@143-174.Invoke(Unit _arg12)
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvokeNoHijackCheck[a,b](AsyncActivation`1 ctxt, FSharpFunc`2 userCode, b result1)
   at <StartupCode$FSharp-Editor>.$FSharpCodeLensService.clo@142-172.Invoke(AsyncActivation`1 ctxt)
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction)
[F#][INFO 07:18:27 PM] Rechecking code due to buffer edit!
[F#][ERROR 07:18:27 PM] Line Lens startup failed with: System.ArgumentException: The option value was None
Parameter name: option
   at Microsoft.FSharp.Core.OptionModule.GetValue[T](FSharpOption`1 option)
   at System.Lazy`1.CreateValue()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Lazy`1.get_Value()
   at <StartupCode$FSharp-Editor>.$FSharpCodeLensService.clo@143-174.Invoke(Unit _arg12)
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvokeNoHijackCheck[a,b](AsyncActivation`1 ctxt, FSharpFunc`2 userCode, b result1)
   at <StartupCode$FSharp-Editor>.$FSharpCodeLensService.clo@142-172.Invoke(AsyncActivation`1 ctxt)
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction)
[F#][INFO 07:18:27 PM] Rechecking code due to buffer edit!
[F#][ERROR 07:18:27 PM] Line Lens startup failed with: System.ArgumentException: The option value was None
Parameter name: option
   at Microsoft.FSharp.Core.OptionModule.GetValue[T](FSharpOption`1 option)
   at System.Lazy`1.CreateValue()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Lazy`1.get_Value()
   at <StartupCode$FSharp-Editor>.$FSharpCodeLensService.clo@143-174.Invoke(Unit _arg12)
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvokeNoHijackCheck[a,b](AsyncActivation`1 ctxt, FSharpFunc`2 userCode, b result1)
   at <StartupCode$FSharp-Editor>.$FSharpCodeLensService.clo@142-172.Invoke(AsyncActivation`1 ctxt)
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction)
[F#][INFO 07:18:28 PM] Rechecking code due to buffer edit!
[F#][ERROR 07:18:28 PM] Line Lens startup failed with: System.ArgumentException: The option value was None
Parameter name: option
   at Microsoft.FSharp.Core.OptionModule.GetValue[T](FSharpOption`1 option)
   at System.Lazy`1.CreateValue()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Lazy`1.get_Value()
   at <StartupCode$FSharp-Editor>.$FSharpCodeLensService.clo@143-174.Invoke(Unit _arg12)
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvokeNoHijackCheck[a,b](AsyncActivation`1 ctxt, FSharpFunc`2 userCode, b result1)
   at <StartupCode$FSharp-Editor>.$FSharpCodeLensService.clo@142-172.Invoke(AsyncActivation`1 ctxt)
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction)
[F#][INFO 07:18:29 PM] Rechecking code due to buffer edit!
[F#][ERROR 07:18:29 PM] Line Lens startup failed with: System.ArgumentException: The option value was None
Parameter name: option
   at Microsoft.FSharp.Core.OptionModule.GetValue[T](FSharpOption`1 option)
   at System.Lazy`1.CreateValue()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Lazy`1.get_Value()
   at <StartupCode$FSharp-Editor>.$FSharpCodeLensService.clo@143-174.Invoke(Unit _arg12)
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvokeNoHijackCheck[a,b](AsyncActivation`1 ctxt, FSharpFunc`2 userCode, b result1)
   at <StartupCode$FSharp-Editor>.$FSharpCodeLensService.clo@142-172.Invoke(AsyncActivation`1 ctxt)
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction)
[F#][INFO 07:18:30 PM] Rechecking code due to buffer edit!
[F#][ERROR 07:18:30 PM] Line Lens startup failed with: System.ArgumentException: The option value was None
Parameter name: option
   at Microsoft.FSharp.Core.OptionModule.GetValue[T](FSharpOption`1 option)
   at System.Lazy`1.CreateValue()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Lazy`1.get_Value()
   at <StartupCode$FSharp-Editor>.$FSharpCodeLensService.clo@143-174.Invoke(Unit _arg12)
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvokeNoHijackCheck[a,b](AsyncActivation`1 ctxt, FSharpFunc`2 userCode, b result1)
   at <StartupCode$FSharp-Editor>.$FSharpCodeLensService.clo@142-172.Invoke(AsyncActivation`1 ctxt)
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction)
[F#][INFO 07:18:31 PM] Rechecking code due to buffer edit!
[F#][ERROR 07:18:31 PM] Line Lens startup failed with: System.ArgumentException: The option value was None
Parameter name: option
   at Microsoft.FSharp.Core.OptionModule.GetValue[T](FSharpOption`1 option)
   at System.Lazy`1.CreateValue()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Lazy`1.get_Value()
   at <StartupCode$FSharp-Editor>.$FSharpCodeLensService.clo@143-174.Invoke(Unit _arg12)
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvokeNoHijackCheck[a,b](AsyncActivation`1 ctxt, FSharpFunc`2 userCode, b result1)
   at <StartupCode$FSharp-Editor>.$FSharpCodeLensService.clo@142-172.Invoke(AsyncActivation`1 ctxt)
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction)
```

Closing and reopening the file fixes it.

#### Repro steps

1. git clone https://github.com/fsprojects/FSharpPlus.git
2. In VS, open FSharpPlus.sln
3. Quickly, before VS restores packages, open a file in the FSharpPlus project, such as Extensions.fs.
4. Observe CodeLens doesn't load, and log messages from Issue 1 are produced.
5. Enable VS option `Reopen documents on solution load`
6. Exit VS with Extensions.fs still open
7. Start VS, open FSharpPlus.sln
8. Observe CodeLens doesn't load, and log messages from Issue 2 are produced.

#### Expected behavior

CodeLens/LineLens annotations should appear.

#### Actual behavior

CodeLens/LineLens annotations fail to appear and errors are produced in output log.

#### Known workarounds

Close and reopen file.
Disable VS option `Reopen documents on solution load`.

#### Related information 

Visual Studio Community 2017 Version 15.9.2

Visual F# Tools nightly 15.8.20181127.3

(Also repros with base Visual F# Tools after uninstalling the nightly via `VSIXInstaller.exe /uninstall:VisualFSharp`.)

**Comment by realvictorprm** [comment]
I would like to fix this as the issue is known to me in different scenarios (I'm the creator of them for Visual Studio :smiley: ). However I don't know why the project information can't be recieved from scratch after a reload.
