### ISSUE TITLE
Exception when pasting JSON into F# code

### ISSUE THREAD

**Issue by vsfeedback** [Microsoft/visualfsharp#6146]
1) Create new F# .Net App
2) Goto line 3 of Program.fs
3) Paste the following JSON:

{
  &quot;internal_statuses&quot;: [
    {
      &quot;id&quot;: 132346,
      &quot;name&quot;: &quot;Not a Priority&quot;,
      &quot;hex_color&quot;: &quot;#FFCC00&quot;,
      &quot;position&quot;: 0
    }
  }
}

Result:
---------------------------
Microsoft Visual Studio
---------------------------
An exception has been encountered. This may be caused by an extension.

You can get more information by examining the file 'C:\Users\****\AppData\Roaming\Microsoft\VisualStudio\16.0_d67c1b72\ActivityLog.xml'.
---------------------------
OK   
---------------------------

ActivityLog shows this callstack:
System.NullReferenceException: Object reference not set to an instance of an object. at Microsoft.CodeAnalysis.Editor.Implementation.Formatting.FormatCommandHandler.ExecuteCommandWorker(PasteCommandArgs args, Action nextHandler, CancellationToken cancellationToken) 
at Microsoft.CodeAnalysis.Editor.Implementation.Formatting.FormatCommandHandler.ExecuteCommand(PasteCommandArgs args, Action nextHandler, CommandExecutionContext context) 
at Microsoft.VisualStudio.Commanding.CommandHandlerExtensions.ExecuteCommand[T](ICommandHandler commandHandler, T args, Action nextCommandHandler, CommandExecutionContext executionContext)
at Microsoft.VisualStudio.UI.Text.Commanding.Implementation.EditorCommandHandlerService.&lt;&gt;c__DisplayClass13_1`1.&lt;Execute&gt;b__1() 
at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.CallExtensionPoint(Object errorSource, Action call, Predicate`1 exceptionFilter)
--- End of stack trace from previous location where exception was thrown --- at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/426010/exception-when-pasting-json-into-f-code.html
VSTS ticketId: 765634_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by cartermp** [comment]
Can reproduce, but this only seems to happen once per VS session. The call stack doesn't indicate anything F#-related, so I'll keep this open but it's quite low priority
