### ISSUE TITLE
Catalog of unstable tests [Memory leak, Async, Choice], causing build failures

### ISSUE THREAD

**Issue by OmarTawfik** [Microsoft/visualfsharp#811]
The test "Async.AwaitWaitHandle does not leak memory" at line 204 of:
https://github.com/Microsoft/visualfsharp/blob/master/src/fsharp/FSharp.Core.Unittests/FSharp.Core/Microsoft.FSharp.Control/AsyncModule.fs

Fails about once every 1,000 times, which causes random builds to fail. Root cause should be investigated, and if it was a test issue, test should be fixed. The test currently runs 100 iterations, and fails if any of them fail, which means about 1 build failure every 10 builds.

**Comment by dsyme** [comment]
We also have this intermittent failure:
```
[00:41:46] 1) Error : FSharp.Core.Unittests.FSharp_Core.Microsoft_FSharp_Control.AsyncModule.Async.Choice specification test
[00:41:46] System.Exception : Falsifiable, after 58 tests (0 shrinks) (StdGen (1910982604,296182551)):
[00:41:46] Original:
[00:41:46] ChoiceWorkflow
[00:41:46]   ([SomeResultAfter -7; SomeResultAfter 4; NoneResultAfter -1; ExceptionAfter -2;
[00:41:46]     NoneResultAfter -4; ExceptionAfter -10; ExceptionAfter 9; NoneResultAfter -9;
[00:41:46]     NoneResultAfter 10; SomeResultAfter -8],Some -14)
[00:41:46] with exception:
[00:41:46] NUnit.Framework.AssertionException:   Expected: 4000
```

**Comment by dsyme** [comment]
Another intermittent test failure, again may indicate a timing issue or race condition

```
[00:41:28] 1) Failed : FSharp.Core.Unittests.FSharp_Core.Microsoft_FSharp_Control.AsyncModule.OnCancel.RaceBetweenCancellationHandlerAndDisposingHandlerRegistration
[00:41:28]   Expected: True
[00:41:28]   But was:  False
[00:41:28] at <StartupCode$FSharp-Core-Unittests>.$AsyncModule.test@286-22(Unit unitVar0) in C:\projects\visualfsharp-3dtit\src\fsharp\FSharp.Core.Unittests\FSharp.Core\Microsoft.FSharp.Control\AsyncModule.fs:line 299
[00:41:28] at FSharp.Core.Unittests.FSharp_Core.Microsoft_F
[00:41:28] Sharp_Control.AsyncModule.OnCancel.RaceBetweenCancellationHandlerAndDisposingHandlerRegistration() in C:\projects\visualfsharp-3dtit\src\fsharp\FSharp.Core.Unittests\FSharp.Core\Microsoft.FSharp.Control\AsyncModule.fs:line 300
```

**Comment by dsyme** [comment]
Another one:
```
[00:34:18] 1) Error : Tests.LanguageService.Script.UsingMSBuild.TypeProvider.Disposal.SmokeTest2
[00:34:18] System.Reflection.TargetInvocationException : Exception has been thrown by the target of an invocation.
[00:34:18]   ----> System.Exception : expected configuration object to be disposed
[00:34:18]    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
[00:34:18]    at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
[00:34:18]    at System.Reflecti
[00:34:18] on.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

**Comment by dsyme** [comment]
Closing this as I haven't seen these intabilities in a while
