### ISSUE TITLE
Embedding an untyped quotation in a typed quotation results in ArgumentException

### ISSUE THREAD

**Issue by latkin** [Microsoft/visualfsharp#89]
This repros back to F# 3.0 at least. Compiles fine, but throws at runtime.

```fsharp
<@ <@@ 100 @@> @>
```
```
System.ArgumentException: Type mismatch when building 'expr': the expression has the wrong type. Expected 'Microsoft.FSharp.Quotations.FSharpExpr', but received type 'Microsoft.FSharp.Quotations.FSharpExpr`1[System.Int32]'.
Parameter name: receivedType
   at Microsoft.FSharp.Quotations.PatternsModule.checkTypesSR[a](Type expectedType, Type receivedType, a name, String threeHoleSR)
   at Microsoft.FSharp.Quotations.PatternsModule.cast[T](FSharpExpr expr)
   at <StartupCode$FSI_0002>.$FSI_0002.main@()
```

**Comment by forki** [comment]
What is the expected behavior?

**Comment by latkin** [comment]
```fsharp
<@@ <@ 100 @> @@>   // works, Expr
<@@ <@@ 100 @@> @@> // works, Expr
<@ <@ 100 @> @>     // works, Expr<Expr<int>>
<@ <@@ 100 @@> @>   // fails, expecting Expr<Expr>
```
